### ISSUE TITLE
exchangeRate: Add patterns properties to validate amount_CODE fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#105]
The [exchangeRate extension documentation](https://github.com/open-contracting-extensions/ocds_exchangeRate_extension) describes an approach for expressing alternative currency values:

>...applications and publishers are encouraged to adopt the following convention for including multiple currency values within the value object.
>
>* `amount` should always be the value in the currency specified by currency.
>* `amount_CODE` can be used to provide the amount in an alternative currency, where >'CODE' is the ISO4217 code of that currency.

Currently there is no validation in the schema for the `amount_CODE` fields, so they would be flagged as additional fields by the Data Review Tool and not validated.

This is a similar issue to language suffixed fields, which are validated by a pattern property.

This issue is to add a pattern property to the extension schema so `amount_CODE` fields can be validated.

**Comment by jpmckinney** [comment]
I did this as part of https://github.com/open-contracting/standard-maintenance-scripts/issues/9
