### ISSUE TITLE
metrics: replace `quantity` with `measure` and `unit` in example

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#106]
The forecasts examples in the metrics extension readme includes a `quantity` key on the observation object.

Per the schema (and the physical progress example) this should be `measure` with an optional `unit` specified.

**Comment by jpmckinney** [comment]
I renamed quantity to measure as part of https://github.com/open-contracting/standard-maintenance-scripts/issues/9. I didn't add unit though.
