### ISSUE TITLE
requirements: Add `relatedRequirementID` to metrics

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#107]
The metrics extension readme describes how the extension can be used with the requirements extension:

> Metrics can be used along with the **requirements extension** which will add a 'relatedRequirementID' property to metrics.
> 
> With the requirements extension, bids, awards and contracts can include a `RequirementResponse` indicating the values against each metric that a supplier intends to meet.
> 
> This can allow a degree of comparison between performance anticipated at bid, award, contract and implementation phases.

The requirements extension does not currently add the `relatedRequirementID` property to metrics. I think the reason this wasn't added is because it would cause problems applying the requirements extension to the schema if the metrics extension wasn't also declared.

One solution could be to create a 'metrics-requirements' extension with the metrics and requirements extensions listed in the `dependencies` in `extension.json`, which could add the new property.

Another option is just to add the field in the metrics extension and explain in the schema description and/or extension documentation that this field is only applicable when the requirements extension is also used.

**Comment by jpmckinney** [comment]
In similar cases (I think it was bids or lots), we added support for other extensions on the 'host' extension, so I suggest adding that field on the metrics extension.

**Comment by jpmckinney** [comment]
Also, we have `relatedLot`, etc. not `relatedLotID`. I suggest naming it `relatedRequirement`.

**Comment by PaulBoroday** [comment]
@duncandewhurst in extensions' [description](https://github.com/open-contracting-extensions/ocds_metrics_extension) it's not precisely clear where this _relatedRequirement_ (I agree with @jpmckinney ) should be added... What is your intention in this respect?

From one hand it could be an attribute of the _metric_ itself:

```
{
  "targets": [
    {
      "id": "001",
      "title": "Products' metrics",
      "description": "Minimum technical requirements",
      "relatedRequirement": "007-1-2"
      "observations": [
        {
          "id": "001-1",
          "note": "Diagonal",
          "measure": 15,
          "unit": {
            "id": "",
            "name": "inches"
          }
        }
      ]
    }
  ]
}
```
On another hand, using _metrics_ we can describe several _observations_ under one sigle _metric_. And each such _observation_ can be related to different _requirement_. In that case it seems better to have _relatedRequirement_ as an attribute of _observation_: 

```
{
  "targets": [
    {
      "id": "001",
      "title": "Products' metrics",
      "description": "Minimum technical requirements",
      "observations": [
        {
          "id": "001-1",
          "note": "Diagonal",
          "measure": 15,
          "unit": {
            "id": "",
            "name": "inches"
          },
          "relatedRequirement": "007-1-2"
        },
        {
          "id": "001-2",
          "note": "HDD Volume",
          "measure": 102400,
          "unit": {
            "id": "",
            "name": "Mbyte"
          },
          "relatedRequirement": "007-1-4"
        }
      ]
    }
  ]
}
```

My second question would be: what is your understanding of this relationship between _metrics_ and _requirements_? 

Option 1: we have a number of _requirements_ in the _tender_ and relevant set of _requirementResonses_ in _bid_. So we are able to formulate _agreedMetrics_ for the _contract_ where such _agreedMetrics_ will be based on _values_, received against certain _requirements_, indicated with _relatedRequirement_ for each _metric/observation_ (depending on your opinion). 

Option 2: we have a number of _metrics_ as a _targets_ of our _tender_. And we want to extract data from _tenderer_ having strong relation of those data with our _targets_.  We can use _relatedRequirement_ for _metric/observation_ (like it is shown on my examples above) to clarify, how the achievement of these _targets_ will be measured during the evaluation of _bids_ received. 

Speaking in json it would be the following: 

```
{
  "targets": [
    {
      "id": "001",
      "title": "Products' metrics",
      "description": "Minimum technical requirements",
      "observations": [
        {
          "id": "001-1",
          "note": "Diagonal",
          "measure": 15.0,
          "unit": {
            "id": "",
            "name": "inches"
          },
          "relatedRequirementID": "007-1-2"
        }
      ]
    }
  ],
  "criteria": [
    {
      "id": "007",
      "title": "Characteristics",
      "requirementGroups": [
        {
          "id": "007-1",
          "requirements": [
            {
              "id": "007-1-2",
              "title": "Diagonal",
              "dataType": "number",
              "minValue": 15.0
            }
          ]
        }
      ]
    }
  ]
}
```

As you can notice, plenty of tasty benefits outcoming from option 2. But I would say that I like option 1 less. It always depends on the issue you are trying to solve. At the moment we faced with both issues and I'm wondering what is your vision of how it should be done in this extension...

**Comment by duncandewhurst** [comment]
Thanks @PaulBoroday.

Regarding the location of `relatedRequirement`, since a requirement is described as:

> An atomic requirement. Requirements can specify the expected value that the response has to contain, or a range of threshold values within which the response has to fit in. The requirement may apply to a certain period of time.

This seems to map best to `observation` rather than `metric`.

Regarding the examples you prepared:

* The metrics extension is intended to describe targets and actuals for the **performance of the contract** rather than for attributes of the items being procured. Examples we have considered include reporting on the progress of construction against a schedule and reporting on progress against social value targets, such as the number of apprenticeships created as the result of a project.

* Per https://github.com/open-contracting/ocds-extensions/issues/4 the requirements extension is used to describe qualification/eligibility criteria for bidders and bids, rather than selection or award criteria

So, this is closer to the Option 1 you described, but with the clarification that metrics relate the performance of the contract rather than to attributes of the items being procured.

I also wanted to highlight that the example given of a 'minimum technical requirements' metric with two observations measuring different attributes (diagonal size and HDD volume) is not how we expected the metrics extension to be used, rather observations should be measures of the same property, which can be disaggregated by time or another dimension.

There is a separate discussion in https://github.com/open-contracting/standard/issues/499 on developing an extension to describe selection or award criteria, which may be of interest.

**Comment by jpmckinney** [comment]
For award criteria, the following extension was recently drafted for OCDS for EU. It works for TED and eForms, which are both fairly generic: https://github.com/open-contracting-extensions/ocds_awardCriteria_extension

**Comment by jpmckinney** [comment]
The content in the issue description was removed in https://github.com/open-contracting-extensions/ocds_metrics_extension/pull/24 in order to close #123 (which was not aware of this issue).

The goal of the requirements extension is to match CCCEV. I'm not entirely clear on the use cases or relating metrics to requirements - and that seems to be shared by other contributors to this issue.

As there is no longer a bug to address, I'm closing.
