### ISSUE TITLE
Performance failures: Add relatedTransactions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#108]
During the development process of the PPP extension the following need was expressed:

> Linking a reported performance failure to the transactions for the payment of any associated penalties.

We didn't find any examples of source data where this link existed, so this issue is to gather any examples of such data, or any specific use cases for this link.

**Comment by jpmckinney** [comment]
Closing as no examples surfaced in 9 months. Can re-open later.
