### ISSUE TITLE
Lots: Add `tender.status` guidance

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/ocds-extensions#113]
We had a question about how `tender.status` should be populated when using lots (which each have their own status).

Advice given on the helpdesk was:

> tender.status is meant to represent the status of the tendering procedure as a whole. As such, if any lots are awarded, the tender.status will be 'complete'. Otherwise, if any lots are unsuccessful, it is 'unsuccessful'. Finally, if all lots are cancelled (the last possible condition), it is 'cancelled'. Prior to there being a result for all lots, 'planning', 'planned' and 'active' codes are used as usual.

I agree with this advice, although I feel we should clarify if there is a case where multiple lots have different statuses e.g. Lot 1 is unsuccessful but Lot 2 is complete.

**Comment by jpmckinney** [comment]
If *any* (i.e. at least one) lot is awarded or successful, then the tender is successful.
