### ISSUE TITLE
Location: The same item can be delivered to multiple addresses

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#115]
See https://github.com/open-contracting/european-union-support/issues/19

cc @ColinMaudry

**Comment by duncandewhurst** [comment]
Clarifying that the action required here is to add the `tender.deliveryLocations` property from the [EU extension](https://extensions.open-contracting.org/en/extensions/eu/1.1/) at the same time as merging the location extension into the schema.

**Comment by jpmckinney** [comment]
Note: EU extension has `deliveryAddresses` but not `deliveryLocations`.

We added it in the EU-specific extension rather than the Location extension, because having both `deliveryLocation` and `deliveryLocations` doesn't make much sense. We should deprecate the singular.

**Comment by duncandewhurst** [comment]
Closing since https://github.com/open-contracting-extensions/ocds_location_extension/pull/34 is merged
