### ISSUE TITLE
participationFees: Adding id to changed merging behavior

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#118]
Before 1.1.3, participation fees had no `id` field, which meant the array was merged as a whole. An `id` field was added in 1.1.3 #48, per the schema style guide at the time.

However, this had the effect of changing the merging behavior to the identifier merge strategy.

To restore the original behavior, we can either:

1. Remove the `id` field
1. Add `"wholeListMerge": true`
    * We would also remove the suggestion that the `id` field will be required in future versions, which was added more recently in response to @yolile's comment in #48 

@duncandewhurst @yolile What is your preference?

**Comment by jpmckinney** [comment]
I double checked, and I don't think any other `id` fields were added to extensions (grepping for `\*.*add.*\bid\b`).

**Comment by yolile** [comment]
@jpmckinney right now, without the id field, if you have more than one item in the participation fees array CoVe report them as duplication (even if they are different)

**Comment by jpmckinney** [comment]
Can you report that issue on the CoVE repo?

**Comment by yolile** [comment]
Already reported https://github.com/OpenDataServices/cove/issues/1246 for the array of strings case, but now updated with this case too

**Comment by duncandewhurst** [comment]
I prefer 2. to keep consistency of structure (if not merging strategy) with other arrays.

Also, if anyone extended participation fees to include a property which is an array then an `id` field would be necessary for flattening.

**Comment by jpmckinney** [comment]
Oops, we actually already set `wholeListMerge` in 1.1.4. No issue here, then!
