### ISSUE TITLE
partyScale: codelist values are translated in main page, Spanish version

### ISSUE THREAD

**Issue by romifz** [open-contracting/ocds-extensions#119]
The values of the `scale` property are translated:

![screenshot-extensions open-contracting org-2019 11 13-14_27_45](https://user-images.githubusercontent.com/1881108/68788232-c494e080-0621-11ea-9612-96bbcf28ebba.png)

I fear this could mislead readers about the allowed values for `scale`.

**Comment by jpmckinney** [comment]
https://extensions.open-contracting.org/es/extensions/partyScale/master/

Thanks for reporting, I will fix that.

**Comment by jpmckinney** [comment]
Fixed in e0e2359. I'll need to push all the new text for translation, but I think we can wait until we have more to translate from other extensions (unless there is an urgent need).
