### ISSUE TITLE
Bids: include array of items 

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#126]
When a tenderer submit a bid for an item this bid may include, besides the total amount of the bid, also the product specification of the item as the brand, model, etc. And it also may include the unit.name and unit.value of it. 

For the product specification the local [items attributes extension](https://gitlab.com/dncp-opendata/ocds_item_attributes_extension) exists.

The proposal is to add the items array into the Bid object to indicate the specifications and units of the bidding items.

cc @jpmckinney

**Comment by jpmckinney** [comment]
To work through some more concrete examples:

- In a maintenance service contract for printers, a procuring entity might have lots for e.g. Canon printers, Brother printers, etc. These brand names would be part of a product description.
- In a contract for new printers, a procuring entity might have lots for printers in general (to avoid anti-competitive / illegal practices). These might not have any detailed product descriptions.
- In either case, however, it should be possible to indicate the unit prices related to the items in any lot, e.g. hourly rate for printer maintenance or purchasing price per printer.
- In either case, in the award, it is similarly useful to indicate this information, especially in cases where bids data isn't available. (When bids data is available, the award might just be repeating the information from the winning bid, but that is okay).

**Comment by yolile** [comment]
Extension drafted [here](https://gitlab.com/dncp-opendata/ocds_bid_items_extension)

**Comment by duncandewhurst** [comment]
@jpmckinney any concerns about merging the `bid_items_extension` into the bids extension?

**Comment by jpmckinney** [comment]
@duncandewhurst Fine with me. Please review the field title/description when making the PR.

**Comment by yolile** [comment]
🎉
