### ISSUE TITLE
Lots: Add `Lot.Buyer`

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/ocds-extensions#127]
We have a case with a publisher where a procurement process is treated as a "package" of different lots. Each of these lots will have different buyers, and suppliers will coordinate with each of the individual buyers during the procurement process. In this case, having an optional `Lot.Buyer` field will support modelling this approach to procurement.

It may be the case that an array (`Lot.Buyers`) would be more appropriate, but there isn't any evidence of that use-case yet.

**Comment by duncandewhurst** [comment]
@jpmckinney do we need to do any further research on this or is it ready to create a PR?

**Comment by jpmckinney** [comment]
I think this is fine to go ahead. Even in the case of multiple buyers for one lot, there is typically a "main" buyer and/or all the buyers are involved in the lot (similar to the cases of joint procurement, framework agreements, etc.).
