### ISSUE TITLE
unstructuredChanges: Add more context to readme

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#133]
We should add more context on when this extension might be appropriate. We can describe how the form works in the EU as an example, and some of the limitations in terms of data quality (as described in https://github.com/open-contracting-extensions/european-union/issues/63), which make use of this extension necessary.

cc @ColinMaudry

**Comment by ColinMaudry** [comment]
If I remember well, the problem with the EU approach is that it requires the users to be quite accurate when they describe the field to be edited. They must specify:

- the section number in the notice
- the lot
- the "place of text to be modified" (the label of the field)

Ideally, we could automatically infer the TED XML element and the corresponding OCDS field targeted by the "corrigendum" and make a new OCDS release that express the changes.

However, we don't expect this information to be accurate enough to be relied upon. We consequently mirrored the EU data structure in [the `unstructuredChange` object](https://github.com/open-contracting-extensions/ocds_unstructuredChanges_extension/) to ensure the details of the modification are stored in OCDS. However, this information is not used to take advantage of the [OCDS data update mechanisms](https://standard.open-contracting.org/latest/en/schema/reference/#release-handling) and is consequently lost for data analysis.

Well, I think I remember well :sweat_smile:

**Comment by jpmckinney** [comment]
Yes, I think some additional context we want to add is something like:

> In many procurement regimes, it is common to amend a procurement notice by describing the changes in words, rather than by re-publishing the full notice. This is because the process is designed for humans: it is easier for a human to read a description of changes, than to calculate the difference between two full notices.
>
> On the other hand, it is easy for a *machine* to calculate the difference between two full notices, but difficult or impossible to interpret a description of changes. There are many ways in which a change description can go wrong, which a human can recover from, but a machine cannot. For example:
>
> [can rewrite some bullet points from https://github.com/open-contracting-extensions/european-union/issues/63]
>
> OCDS is designed to be read by machines. Ideally, the source system from which OCDS data is exported contains the values of each field before and after a change. In that case, you should simply follow the releases and records model [link].
> 
> This extension is intended to be used **only** in cases where a source system doesn't track the values of fields, but instead tracks a description of changes, like in the EU.

What do you think?
