### ISSUE TITLE
Party scale: add a code to represent an individual

### ISSUE THREAD

**Issue by romifz** [open-contracting/ocds-extensions#134]
The DGCP in the Dominican Republic created their own [party scale version](https://github.com/dgcpcompraspublicas/ocds_partyDetails_scale_extension) that adds the "person" code to the partyScale codelist.

In other jurisdictions the "micro" code may apply for the case of individuals acting as suppliers. However, in the Dominican Republic a supplier needs a certification from the Ministry of Industry to be classified as "micro" (up to 10 employees and annual gross sales of up to RD$ 8,000,000), whereas a "person" is an individual registered in the Registry of Providers.

We need to consider if a new code to represent individuals is needed. The code "selfEmployed" has been suggested by @jpmckinney instead of "person".

**Comment by jpmckinney** [comment]
I'm fine with my suggestion :) @romifz Do you want any other input before making a PR?
