### ISSUE TITLE
Project: Align with newer OC4IDS guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#135]
The readme could better clarify the difference between `planning.project` and `planning.budget.project`. I think OC4IDS already has relevant content.

I think we also agreed in OC4IDS that COFOG is not appropriate for sector classifications. The example in this extension (that I recently moved from the ocds_ppp_extension) should be updated.

**Comment by yolile** [comment]
We should also add an example for an OC4IDS project

**Comment by odscjen** [comment]
@duncandewhurst just checking if this is still on your radar as the assignee, https://github.com/open-contracting/standard/issues/1484 is dependent on this issue being addressed first

**Comment by duncandewhurst** [comment]
> I think we also agreed in OC4IDS that COFOG is not appropriate for sector classifications. The example in this extension (that I recently moved from the ocds_ppp_extension) should be updated.

Yep, that's correct. The question is what to replace it with! In https://github.com/open-contracting/infrastructure/issues/16 we looked at various (infrastructure project) sector classification schemes before deciding to author our own for OC4IDS. None of the schemes discussed in that issue appear in the classificationScheme codelist. Should we add the OC4IDS sector codelist to the classificationScheme codelist? (seems a bit circular...)

**Comment by jpmckinney** [comment]
I might be missing something obvious, but what is the circularity?

I think it's okay for an OCDS extension to treat OC4IDS as an external scheme.

**Comment by duncandewhurst** [comment]
That was all. Great. I'll add it then.

**Comment by duncandewhurst** [comment]
I've prepared a PR for this issue: https://github.com/open-contracting-extensions/ocds_project_extension/pull/29. Should I review the field titles and descriptions against the style guide as part of the same PR (per https://github.com/open-contracting/standard/issues/1484#issuecomment-1581314136)?

**Comment by jpmckinney** [comment]
Let's do separate PRs. That PR looks substantial as-is.
