### ISSUE TITLE
unstructuredChanges: `date` is not guaranteed to have a meaningful time component

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#140]
> Where there are changes made to dates via an F14, time (/CHANGES/CHANGE/[OLD_VALUE|NEW_VALUE]/TIME) is optional (as it will not apply to some fields), but it is required by the OCDS schema. In other forms, we always know whether a particular date is start or end and add T00:00:00 or T23:59:59 accordingly. As /CHANGES/CHANGE/WHERE/LABEL is also optional, we may not know here which date within a numbered section is being corrected, and it's also possible for an invalid section to have been specified in /CHANGES/CHANGE/WHERE/SECTION. Can advise on whether it is best to leave the time off (breaking the schema) or add either or the times above (not knowing which is more appropriate)? 

@colinmaudry Should we remove the `"format": "date-time"` in that case?

**Comment by ColinMaudry** [comment]
Then there won't be any format validation, that sounds risky. Can't we use a regex that would allow both ISO date and datetime?

Wait a min, I'll give it a shot :runner:

**Comment by ColinMaudry** [comment]
Here you go (inspired by https://stackoverflow.com/a/3143231):

`^\d{4}-[01]\d-[0-3]\d(T[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:?[0-5]\d|Z))?`

**Comment by ColinMaudry** [comment]
```
{
    "format": "date-time"
}
```

can consequently be replaced with

```
{
   "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
}
```

**Comment by jpmckinney** [comment]
You're right – that's better than no validation :)
