### ISSUE TITLE
participationFees: Payment address and payee

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#144]
The [Himachal Pradesh Govt Tenders Information System](https://hptenders.gov.in/nicgep/app) includes the payment address and payee for participation fees.

**Payment address examples:**

Jawali
Nahan
Salooni 

(Names of towns in Himachal Pradesh)

**Payee examples:**

EXECUTIVE ENGINEER HPPWD DIVISION JAWALI
EE Nahan
Executive Engineer Salooni Division HPPWD Salooni

**Modelling**

Helpdesk recommended adding a `paymentAddress` property (`Address` object) and a `payee` property (`OrganizationReference` object) to the `ParticipationFee` object.

**Comment by jpmckinney** [comment]
Can you link the CRM issue? I can't find the discussion.

**Comment by duncandewhurst** [comment]
The recommendations were made in [this Google Sheet](https://docs.google.com/spreadsheets/d/1Qg04H-uFnuAAPZOErr0pd4Plzbm7yyLuL2x2ik1jIQM/edit#gid=48229706) linked from [this CRM issue update](https://crm.open-contracting.org/issues/6407#note-3).

The publisher originally proposed two text fields:

* `tender/participationFees/0/paymentAt` (for the payment address)
* `tender/participationFees/0/paymentTo` (for the payee)

It's probably easiest to get the context from looking at the source system, as the publisher is scraping the data from the front-end before converting it to OCDS format. Unfortunately the system doesn't have persistent URLs, so you need to:

* Go to: https://hptenders.gov.in/nicgep/app
* Click 'Tenders in Archive' in the sidebar
* Enter a tender ID (e.g. 2017_PWD_16278_1), complete the Captcha and click 'Search'
* Click the link in the 'Title and Ref.No./Tender ID' column

The above fields appear in the 'Tender Fee Details' section.

**Comment by jpmckinney** [comment]
For the EU profile, similar information is disclosed as an organization, e.g. with the role 'processContactPoint' ("A contact point dedicated to this contracting process") or 'reviewContactPoint' ("The service from which information about the review procedure can be obtained"). In this case, there could be a 'paymentContactPoint'.

**Comment by neelima-j** [comment]
[The eProcurement System of the Government of Assam](https://assamtenders.gov.in/nicgep/app) also publishes the fields `EMD Payable To` and `EMD Payable At`, where EMD is Earnest Money Deposit.

**Example**:
When the EMD is to be paid as a demand draft, the name and address of the payee are published in the notice. 
Tender ID	2018_ICD_8933_2
`EMD Payable To` Assam Industrial Development Corporation Ltd. 
`EMD Payable At` Guwahati

When the EMD is to be paid online on the portal, the tender displays no information for these fields:
Tender ID   2022_IWT_26130_1
`EMD Payable To`  Nil
`EMD Payable At`  Nil


The mapping advice for these fields is the same as it was for Himachal Pradesh: [ mapping feedback document](https://docs.google.com/document/d/1emMY3TYhBHxsAHisGBOiBJYi1zhaj_N3aqtt4At7Cts/edit#) as reviewed in 
the CRM issue [#8230](https://crm.open-contracting.org/issues/8230)

**Comment by jpmckinney** [comment]
FYI you can type CRM-8230 and it will autolink :)
