### ISSUE TITLE
participationFees: Exemption allowed

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#145]
The [Himachal Pradesh Govt Tenders Information System](https://hptenders.gov.in/nicgep/app) includes the a boolean `exemptionAllowed` field for participation fees.

**Comment by jpmckinney** [comment]
What are the semantics? Without knowing how to qualify or apply for an exemption, it's not clear how useful this data element is.

**Comment by jpmckinney** [comment]
Closing as the semantics are unclear.
