### ISSUE TITLE
Bids: extend Statistic with .valueGross

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/ocds-extensions#146]
This would be useful to map the gross award values of TED form F18.

**Comment by jpmckinney** [comment]
Background:

Publisher:

> F18 allows contract values to be specified as including or excluding VAT, and if including then what the percentage is, all in V.4. I can't see anything similar in R2.0.9 or the OCDS.

@ColinMaudry:

> Documenting VAT has been discussed at length here (https://github.com/open-contracting/standard/issues/383#issuecomment-468534963) and evolved to discussing what `amount` actually means here: https://github.com/open-contracting/standard/issues/817. Since R2.0.8 seems to specify both net and gross, I suggest the following structure:
>
> - calculate (if necessary) and map the net amount to `amount`
> - calculate and map the VAT-included amount to `amountGross` (there may be no
> 
> Given the input you describe, you'll either end with both `amount` and `amountGross` fields filled, or only with `amount`.

Publisher:

> These could also be specified as a range (lowest offer to highest offer). The equivalent values in F03 are mapped to bids.statistics.value. I assume we should extend this object to also include valueGross, but could you comment on/confirm that?
