### ISSUE TITLE
Add a new documentAvailabilityPeriod to the communication extension

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/ocds-extensions#147]
It comes from TED form F17, IV.3.3.

**Comment by jpmckinney** [comment]
We typically follow a pattern of suffixing "Period" to the end of period fields, and it's about the availability of *documents* (which might be also described in the documents array in other OCDS data), not *documentation*. So, I think `tender.communication.documentAvailabilityPeriod` is better.

**Comment by jpmckinney** [comment]
[EN_F17.pdf](https://github.com/open-contracting/ocds-extensions/files/5197998/EN_F17.pdf)

**Comment by jpmckinney** [comment]
![Screen Shot 2021-01-29 at 4 16 28 PM](https://user-images.githubusercontent.com/26463/106328173-5a2f8680-624d-11eb-8811-acaeaa1010ca.png)

**Comment by jpmckinney** [comment]
Noting that F17 only requires an end date, but we are anticipating that a start date could be disclosed, so are using a Period to avoid having to re-model the field in future.
