### ISSUE TITLE
[subcontracting] Copy some or all the fields to Tender 

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/ocds-extensions#149]

**Comment by ColinMaudry** [comment]
All the fields of the `Subcontracting` don't make sense in the context of `Tender`.

`description` is:

> The description of the part of the contract that the supplier will subcontract to third parties.

That doesn't match the semantics of the content in TED form F17 II.1.7), which refers to the obligations that fall to subcontracting suppliers.

@jpmckinney Do I:

- Change the description of `description` to be more generic and work both in Awards and with the content from F17?
- Create a new subcontracting object with semantics dedicated to Tender and F17 content?
- Do something else?

**Comment by jpmckinney** [comment]
@ColinMaudry Are the other fields relevant to subcontracting in the context of tender? If most would have to change or not all are relevant, I think it's better to have a `SubcontractingTerms` object for `Tender`.

**Comment by ColinMaudry** [comment]
For now we only need SubcontractingTerms.description, so I'll consequently only add this one. We can add more later.

**Comment by ColinMaudry** [comment]
Apparently we already had added `Subcontracting` to Tender. In the EU profile guidance, there is not occurrence of the `subcontracting` being used in `Tender`. I'll replace it with the simpler `SubcontractingTerms`.
