### ISSUE TITLE
Bid Statistics and Details - align example with codelist

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/ocds-extensions#150]
Via the OCDS Helpdesk (paraphrased)

The example data includes a measure for disqualified bids but this is not included in the codelist. The codelist does include `disqualifiedBidders`. Although it is an open codelist it would be best if the example was aligned with codes that were already in the list and present in the documentation.

Should we:
a) change the example to use `disqualifiedBidders`
b) update to codelist to add `disqualifiedBids`

From a surface-level reading I'd imagine there to be a semantic difference between a disqualified bid vs a disqualified bidder, but that might not be the case?

**Comment by jpmckinney** [comment]
@mrshll1001 Can you add a link to the CRM issue? You can write a reference like CRM-999 and it will autolink.

**Comment by jpmckinney** [comment]
Closed by a010c4b

**Comment by jpmckinney** [comment]
Aha, it was CRM-5095
