### ISSUE TITLE
Finance extension: sometimes referred to as "Financing"

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/ocds-extensions#153]
The https://extensions.open-contracting.org/en/extensions/finance/master/schema/ extension is called "finance" in the URL, schema and other places, but is referred to as "Financing" in the headline (and consequently in https://extensions.open-contracting.org/en/extensions/). Is this intentional, or would it be better to use "Finance" everywhere for consistency?

**Comment by jpmckinney** [comment]
Thanks! This will be reflected in the Extension Explorer within 24 hours.
