### ISSUE TITLE
bids: Update documents example

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#154]
The current example uses a code from OCDS for PPPs. However, this would mix documents submitted by the bidder with those authored by the buyer.

OCDS doesn't offer a model for bid assessments, so a compromise that publishers might make is to add such documents to the bid – but this should not be promoted by the documentation.

**Comment by duncandewhurst** [comment]
The `documents` array doesn't seem particularly relevant to the example so I think we can just remove it. Sound good?

**Comment by jpmckinney** [comment]
Sounds good!
