### ISSUE TITLE
Bids: Negotiation results

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#156]
Similar to #155, Indonesia's [LPSE system](https://lpse.lkpp.go.id/eproc4/) also collects structured data on bid evaluation  including the results of price negotiations after the selection of a winner based on quality criteria ([example](https://lpse.lkpp.go.id/eproc4/evaluasi/7012119/hasil)). This process is described in Article 50 (2) of [Presidential Regulation Number 16 of 2018](https://jdih.lkpp.go.id/regulation/download/terjemahan-resmi-peraturan-presiden-nomor-16-tahun-2018/1) and in Section 2.2 of [Chambers's guide](https://www.makarim.com/uploads/131515_INDONESIA%20-%20Public%20Procurement%20&%20Government%20Contracts.pdf).

The negotiated value is separate to the award/contract value so doesn't have a mapping in OCDS.

We could add a `Bid/negotiatedValue` field with the following description, but I'm not sure that is the best approach:

> The total value of bid, after any negotiations.

@jpmckinney what do you think?

cc @pindec

**Comment by jpmckinney** [comment]
Negotiation is common to several procurement procedures. I don't know a scenario where the negotiated value isn't identical to the award value, so I would just set award value. Presently, the `procurementMethodDetails` would indicate whether the procedure was with negotiation or not.

In terms of modelling the presence of negotiation as part of the procedure, we can discuss that in https://github.com/open-contracting/standard/issues/1144

**Comment by jpmckinney** [comment]
Section 2.2 of Chamber's guide has:

> 2.2 negotiating tenders
>
>Generally speaking, the regulation does not allow for price negotiation, except for procurement using a direct appointment, direct procurement and for the procurement of consultancy services. However, under LKPP 14/2012, it is possible for a public tender to have negotiations of the price, provided that fewer than three tender participants submit a price proposal.
>
> Under LKPP 14/2012, the price negotiations must be based on the owner’s estimate, and the total price negotiated cannot be above the total owner’s estimate. However, if all the price proposals are above the owner’s estimate, price negotiations will be conducted with the tender participant who submits the lowest price; if an agreement cannot be reached, then the negotiations will continue with the tender participant who has submitted the second lowest price; and if an agreement cannot be reached with any tender participant, the tender will be deemed to have failed.

**Comment by jpmckinney** [comment]
@duncandewhurst I'm not sure the reference to the presidential regulation is correct. At any rate, there isn't much detail that I can find. The Chamber's guide quoted above mentions LKPP 14/2012, but I can't find an English version. I found this copy hosted on a Bandung website. It's over 1000 pages long, but does mention 'negosiasi' over 400 times: http://ciptakarya.badungkab.go.id/images/gambarmce/Peraturan-Peraturan/PERKA_LKPP_NO.14_TAHUN_2012.pdf

**Comment by jpmckinney** [comment]
> The negotiated value is separate to the award/contract value so doesn't have a mapping in OCDS.

On what is this statement based?

**Comment by duncandewhurst** [comment]
> > The negotiated value is separate to the award/contract value so doesn't have a mapping in OCDS.
> 
> On what is this statement based?

ICW shared an example awards data export from LPSE which includes the following value fields:

* nilai_penawaran (bid value)
* nilai_terkoreksi (corrected value)
* nilai_negosiasi (negotiated value)
* nilai_kontrak (contract value)

> @duncandewhurst I'm not sure the reference to the presidential regulation is correct. At any rate, there isn't much detail that I can find.

The presidential regulation states that, for consultancy contracts:

> clarification and negotiation for the technical and price proposals are made after the end of the objection period.

**Comment by jpmckinney** [comment]
Could you paste the excerpt of the export here?

Thanks – that's at Article 50 (3), not Article 50 (2).

**Comment by duncandewhurst** [comment]
You can find the link in CRM-6782#note-13. I've requested access to the full export to check when `nilai_kontrak` is populated.

kd_tender | kd_rup_paket | kd_paket | tahun_anggaran | nama_satker | nama_klpd | jenis_klpd | pagu | hps | nilai_penawaran | nilai_terkoreksi | nilai_negosiasi | nilai_kontrak | tgl_pengumuman_tender | tgl_penetapan_pemenang | nama_penyedia
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
724262 | 26564662 | 671262 | 2020 | Universitas Airlangga | - | - | 550222200.00 | 550222200.00 | 207267500.00 | 29425000.00 | 29425000.00 | - | 11/04/20 03:00 pm | 2020-12-04 23:59:00.0 | murai batu, cv
724262 | 26564662 | 671262 | 2020 | Universitas Airlangga | - | - | 550222200.00 | 550222200.00 | 246011700.00 | 196027700.00 | 196027700.00 | - | 11/04/20 03:00 pm | 2020-12-04 23:59:00.0 | SAPTA KARYA ABADI
724262 | 26564662 | 671262 | 2020 | Universitas Airlangga | - | - | 550222200.00 | 550222200.00 | 386421818.20 | 42361497.20 | 42361497.20 | - | 11/04/20 03:00 pm | 2020-12-04 23:59:00.0 | CV. PUTRA JAYA SAKTI

**Comment by jpmckinney** [comment]
Thanks, I'll wait for access to the original.

**Comment by duncandewhurst** [comment]
Here's a [copy](https://docs.google.com/spreadsheets/d/1v9BAzWrl0ryKUojwK1eqVMqQftR6ARAnt0MT-oZm-Bo/edit#gid=607341203) to which I added a column to check for differences between the negotiated value and the award value.

There are many differences, but the data looks like it contains duplicates where a contracting process results in awards to more than one supplier.

**Comment by jpmckinney** [comment]
Hmm, the data is confusing. I've updated the last column to express the ratio of contract value to negotiated value as a percentage, and it's anywhere from 0.2% to 20023% of the negotiated value. The average is over 300%. I think we need to better understand the data before drawing any conclusions, because variance of 0.2% to 20023% doesn't make much sense.

**Comment by duncandewhurst** [comment]
I've followed up with ICW in CRM-7877
