### ISSUE TITLE
submissionTerms: define catalog

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/ocds-extensions#159]
Based on https://github.com/open-contracting/standard/issues/396#issuecomment-726399431, we should define electronic catalogs in https://extensions.open-contracting.org/en/extensions/submissionTerms/master/. I suggest using a definition based on https://github.com/open-contracting/standard/pull/1205/commits/d54ca05a29577f14e2c1c098839d297c85730129, e.g. 

_An electronic format (typically prescribed by the buyer) that participants in the contracting process must follow when exchanging information about technical specifications, evaluation criteria, bids, lots, etc._

___

Note: the extension uses "catalogue" while the guidance "catalog". Catalog is more popular in US English, so should be the default option, but I'm not sure whether we don't want to stick to catalogue instead because it is already a field (changing a field has bigger impact than changing documentation) and because it is an EU extension and the EU uses "catalogue".

**Comment by ColinMaudry** [comment]
Beside UK and Scotland, I don't think that submissionTerms extension has been broadly adopted. I suggest:

- we fix the spelling of "catalog" in the schema
- we inform the adopters we know of

**Comment by jpmckinney** [comment]
This extension is planned to be merged into OCDS 1.2: https://github.com/open-contracting/standard/issues/1183

We can make the rename when doing that merge. This is less disruptive to the two publishers, as they can continue using this extension with the original naming. They will only need to rename fields when upgrading to OCDS 1.2.

**Comment by jpmckinney** [comment]
I've added a definiton to the field description, which closes this issue.

https://github.com/open-contracting-extensions/ocds_submissionTerms_extension/commit/db486788f996b2844711b13c51e9bd1371516599
