### ISSUE TITLE
Organization classification: master branch missing

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#160]
I shared the following link with a publisher last month, but now it is broken: https://extensions.open-contracting.org/en/extensions/organizationClassification/master/

Looking at the repository, there is no master branch

**Comment by jpmckinney** [comment]
There is now a 1.1 branch, since the draft 1.2 version removes a codelist. I'll add redirects to the Extension Explorer.

**Comment by jpmckinney** [comment]
The documentation should rebuild in a few minutes. The /master/ URL now renders the latest version (1.1).
