### ISSUE TITLE
techniques: Add tender/techniques/frameworkAgreement/minValue

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#161]
[Form F17](https://simap.ted.europa.eu/documents/10184/49059/sf_017_en.pdf) includes a range for the estimated value of a framework agreement.

UK FTS is publishing `tender/techniques/frameworkAgreement/minimumValue` as an additional field, but we should probably use  `minValue` to align with `tender/minValue`.

cc @odscrachel

**Comment by jpmckinney** [comment]
F17 is one of the defence forms, which uses an older XML schema (R2.0.8), and which was not mapped as part of the profile. The newer schema (R2.0.9) and the eForms schema have no minimum value.

As such, we agreed with Cabinet Office that FTS can add fields for the older schema, but that these will not be documented by the EU profile's extensions. (They can still create their own local extension.)

----

Separately, with the exception of `minValue` and `maxExtentDate`, abbreviations are avoided. I don't think there's an issue with `minimumValue` (rather, there is an issue with `minValue`, which we can't change for backwards-compatibility).

**Comment by duncandewhurst** [comment]
> F17 is one of the defence forms, which uses an older XML schema (R2.0.8), and which was not mapped as part of the profile.

Can this be added to the documentation somewhere?

**Comment by jpmckinney** [comment]
I guess we can add something after "This guidance is based on the TED publication XML schema R2.0.9 (007, 2018-10-30)." on the [landing page](https://standard.open-contracting.org/profiles/eu/latest/en/#technical). How about:

----

It does not cover XML schema R2.0.8, used for the standard forms related to [Directive 2009/81/EC](https://data.europa.eu/eli/dir/2009/81/oj) on the coordination of procedures for the award of certain works contracts, supply contracts and service contracts by contracting authorities or entities in the fields of defence and security:

* F16: Prior information notice for contracts in the field of defence and security
* F17: Contract notice for contracts in the field of defence and security
* F18: Contract award notice for contracts in the field of defence and security
* F19: Subcontract notice

**Comment by duncandewhurst** [comment]
Perfect, thanks!

**Comment by jpmckinney** [comment]
Closed by 38123eb. Will deploy after build.
