### ISSUE TITLE
medicine: Next steps

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#163]
* [x] Delete release-schema-es.json (translate in Transifex once English is finalized)
* [x] extension.json: Delete `es` keys (translate in Transifex)
* [x] extension.json: Update name to "Medicine"
* [x] extension.json: Update description to "Medicine" to "Adds fields to the item object relevant to the procurement of medicines."
* [x] Delete Description column in codelists (add exception in standard-maintenance-scripts)
* [x] Update readme once Google Docs is finalized
* [x] Add to extension registry
* [x] extension.json: Fix documentationUrl, once added to Extension Explorer

**Comment by yolile** [comment]
Done https://extensions.open-contracting.org/en/extensions/medicine/master/
