### ISSUE TITLE
Code tag missing for keywords in beneficialOwners extensions

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/ocds-extensions#164]
In https://extensions.open-contracting.org/en/extensions/beneficialOwners/master/ is missing `<code>beneficialOwners<code>`.

This also implies that the codes that should not be translated are not differentiated in the transifex: https://www.transifex.com/open-contracting-partnership-1/search/?q=source_text%3A%27beneficial+owners%27.

**Comment by jpmckinney** [comment]
I think we should just have it be "beneficial owners" (text), since the first sentence should generally avoid machine text.
