### ISSUE TITLE
Status Details: 'statusDetails' without code tag

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/ocds-extensions#166]
In the first sentence, we have 'statusDetails' field [here](https://extensions.open-contracting.org/en/extensions/statusDetails/master/).

Similar case: https://github.com/open-contracting/ocds-extensions/issues/164

**Comment by jpmckinney** [comment]
I think this is okay, since the sentence is explicitly about the named field. What is the issue?

**Comment by yolile** [comment]
And I see that it actually has the HTML code tag: 
![image](https://user-images.githubusercontent.com/6834122/127542956-e8ed36fb-fb72-46e6-8cc7-f64f0211af2e.png)

**Comment by aguilerapy** [comment]
In [transifex](https://www.transifex.com/open-contracting-partnership-1/ocds-extensions/translate/#es/statusDetails--master--schema/298171027) we don't see the single quotes in 'statusDetails' in this string: "Add a statusDetails field to Tender, Award and Contract object". It is to make it easier to identify which words we should translate and which ones should not, especially for Dulce Areco (those with single quotes refer to field names in the standard, so we should not translate those).

It's an option to define it like this?: "Add a 'statusDetails' field to the Bid, Award and Contract object" (for this and the other first sentences of the other extensions).

**Comment by yolile** [comment]
Ah, you are talking about the extension's description in the `extension.json` file. I don't know what is the rule/format for the descriptions there @jpmckinney

**Comment by jpmckinney** [comment]
Looking at https://github.com/open-contracting/extension_registry/blob/main/build/extensions.json, no extension.json file contains any backticks or single quotes (except for the possessive).

For now, please do not translate camelCase words.
