### ISSUE TITLE
Submission Terms: add a submission address

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#169]
Currently, the [extension](https://extensions.open-contracting.org/en/extensions/submissionTerms/master/) description says:

> Adds a submission terms object to the tender and lot objects, to describe how, when and **where** the tenderers must submit their bids.

However, the extension doesn't have a field for setting **where** the bid should be sent if they are not electronic. 

In countries like [Uruguay (example)](https://www.comprasestatales.gub.uy/ocds/release/llamado-400569) and [Paraguay (example)](https://www.contrataciones.gov.py/datos/api/v3/doc/ocds/releases/id/382899-servicio-vpn-e-internet-alternativo-1-1598279459.40913), this information is currently modeled in `submissionMethodDetails` as semi-structured text, but it would be better to have a place to put the structured information, similar to the [bidOpening](https://extensions.open-contracting.org/en/extensions/bidOpening/master/) extension, but for the bid submission.

**Comment by jpmckinney** [comment]
Sounds good!

cc @ColinMaudry
