### ISSUE TITLE
selectionCriteria: Should this be removed in favor of requirements?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#170]
https://extensions.open-contracting.org/en/extensions/requirements/master/
https://extensions.open-contracting.org/en/extensions/selectionCriteria/master/

If so, we need to update the EU profile.

**Comment by yolile** [comment]
Note that if that is done, we will need to introduce `selectionCriterionType` as part of `requirements`, and add "subcontractor" as another code for `relatesTo`

**Comment by jpmckinney** [comment]
Here's another issue about adding a new field to SelectionCriterion: https://github.com/open-contracting/european-union-support/issues/72/ It might be hard to harmonize the two ways of expression criteria.

**Comment by yolile** [comment]
And another one about adding more fields to the requirements extension https://github.com/open-contracting/ocds-extensions/issues/132 (including criterionType)

**Comment by jpmckinney** [comment]
Yes, instead of comparing requirements (as it is now) to selectionCriteria, we can compare CCCEV to selectionCriteria, and then just improve requirements with the missing parts of CCCEV (and remove some of our own inventions if appropriate).

**Comment by jpmckinney** [comment]
Okay, I'm resolving this issue by having the extensions point to each other, with the suggestion that if your data follows CCCEV, use Requirements, and if not, use Selection criteria.

Since CCCEV is outside our control, I think it's fine to offer our own model – similar to how we have profiles for the EU that aren't expected to be used globally.
