### ISSUE TITLE
Organization classifications: include an example for woman-owned business

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#171]
We have a worked example of woman-owned mapping in the [standard documentation](https://standard.open-contracting.org/latest/en/guidance/map/organization_classifications/#example-2-2-disclosing-data-using-a-local-scheme), but as there is a lot of interest on this topic recently, we could add a specific example into the extension itself, so it would be easier to find when looking for woman related extension. We could also update the extension description to include classifications examples inspired by the first paragraph of the standard documentation [section](https://standard.open-contracting.org/latest/en/guidance/map/organization_classifications/#organization-classifications)

**Comment by jpmckinney** [comment]
I think a short example is fine for the extension. For a longer example, we should just link to the standard docs, to avoid repetition (and potential conflict in future).
