### ISSUE TITLE
Bid opening: Clarify the purpose of the extension

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#172]
From https://github.com/eForms/eForms/issues/287#issuecomment-472822300:

> A clarification is in order here: these fields are not intended to describe the internal procedures of the contracting authority, but rather to inform the public in case a public opening is being held (this is typically used in open procedures).
>
> These fields were very meaningful under paper submission. With eSubmission, their importance is very low. (Even though they may still be used for below-threshold; procurement with non-electronic submission; etc.)

Edit: If the extension *is* intended to describe the internal procedures, then we should add guidance on how to model contracting processes in which different 'envelopes' are opened on different dates. For example, from CRM-7628, Assam's e-procurement system records two bid opening dates for some contracting processes: the technical bid opening date and the price bid opening date.

**Comment by jpmckinney** [comment]
This is only intended for public openings.

**Comment by jpmckinney** [comment]
The notes/semantics in Assam are:

> In case of multiple covers, the financial bid opening date is different than the technical bid opening date. The procuring entity can notify the price bid opening date only after uploading technical evaluation details. I could not find an equivalent field in OCDS nomenclature but this is an essential field.

The bid opening extension only anticipates a single date. https://extensions.open-contracting.org/en/extensions/bidOpening/master/

I would suggest using the bid opening extension for the first date (technical bid opening date), and then milestones for the second date. If we later find that having two dates is a common need, then we can update the extension.

**Comment by duncandewhurst** [comment]
In Assam's case, I don't think the bid opening date relates to a public opening of the bid, rather the date on which the procuring entity will 'open' that part of the bid in the e-procurement system. Is the extension still applicable in that context?

I'm basing the above on this note from the 'no of covers' field in the [additional fields document for Assam](https://docs.google.com/document/d/1Hkk8KjqvfLWAri36z1r0rMzmjM41j_gGY8KhpZAsme8/edit#):

> This refers to segregation of qualification information, technical proposal, financial bid, etc. during bid submission. Traditionally called 'cover' or 'envelope', in e-procurement terms it means folders to be created for bidders to upload their corresponding parts of bid. Generally each folder is opened at a different point in time, sequentially, filtering out a number of bidders at each stage. GePNIC (Assam's e-procurement portal) currently allows up to 4 covers.

**Comment by jpmckinney** [comment]
Hmm, if it's not public then use a milestone. I'm not super clear on the value of this detailed information.

**Comment by jpmckinney** [comment]
I've added the word "public" to the docs and schema in https://github.com/open-contracting-extensions/ocds_bidOpening_extension/commit/9032c03ffd74ded36883da9d59956c406629860a
