### ISSUE TITLE
competitive: Merge with the techniques extension, as they are typically used together

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/ocds-extensions#174]
I just discovered the [competitive extension](https://extensions.open-contracting.org/en/extensions/competitive/master/) that adds a `tender.competitive` boolean field.

Desription of the extension:

> Adds a field to the tender object in a framework agreement call-off to indicate if it is competitive or direct.

Since it's tightly related to framework agreements, I wonder why this field hasn't been added to the [techniques extension](https://github.com/open-contracting-extensions/ocds_techniques_extension) which already has a bunch of fields related to framework agreements.

**Comment by jpmckinney** [comment]
@yolile I think the partner that uses the competitive extension doesn't use the techniques exception?

**Comment by yolile** [comment]
> I think the partner that uses the competitive extension doesn't use the techniques exception?

Yes, it does, but I think the reason is that the techniques extension is used in the framework agreement set up, but the competitive extension is used during call-offs, where the techniques extension is not used anymore

**Comment by ColinMaudry** [comment]
Because it's a new procedure, thus a new `tender`?

**Comment by yolile** [comment]
Yes, in the current version of OCDS we need them to be different procedures, so the framework agreement set up procedure uses the techniques extension to indicate the framework agreement usage and its "rules", and then, the following call-offs to actually buy something from the framework are considered as new procedures that use the competitive field to indicate if they are competitive or not.

**Comment by jpmckinney** [comment]
Strictly speaking, it's the same real-world procedure. In OCDS, however, we issue a new OCID for each call-off. See the definitions at https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/contracting_planning_processes/#contracting-processes-and-planning-processes

**Comment by jpmckinney** [comment]
If both extensions are always used together, then they can be combined. Indeed, our guidance uses both: https://standard.open-contracting.org/latest/en/guidance/map/framework_agreements/

So, I think we can merge competitive into techniques and deprecate competitive (and just leave it around forever, for existing users).

**Comment by yolile** [comment]
I'm not quite convinced to re-use the same `frameworkAgreement` object, as I understand it refers to the first stage of the procedure, and all of its fields are related to that. It could be kind of confusing to have one field that refers to the call-off; for example, it could be interpreted as the framework agreement set up as being competitive or not.

**Comment by jpmckinney** [comment]
I meant to just merge the schemas - no changes to fields.

**Comment by ColinMaudry** [comment]
Yup, when merged `.competitive` would still be in `tender` (and soon in Lot), not in `.frameworkAgreement`.

**Comment by yolile** [comment]
Ah perfect, then yes, it makes sense

**Comment by jpmckinney** [comment]
I've merged competitive into techniques, removed competitive from the registry, and updated competitive's documentationUrl to point to GitHub instead of the Extension Explorer.
