### ISSUE TITLE
metrics: use Unit definition

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-extensions#179]
From https://github.com/open-contracting/standard/issues/1107#issuecomment-799708472:

> For the metrics extension, we can rename master to 1.1 (and update the registry), and then add a 1.2 branch that references the Unit definition.

**Comment by duncandewhurst** [comment]
@odscjen please could you create the 1.2 branch with the schema change and then assign to me to update the registry. Thanks!

**Comment by duncandewhurst** [comment]
@yolile @jpmckinney I've renamed master to 1.1 locally and pushed it to Github, but I'm unable to delete the master branch as I don't have access to the repository settings. Please could one of you do that?

I've also created a PR to update the extensions registry: https://github.com/open-contracting/extension_registry/pull/141

**Comment by jpmckinney** [comment]
> Please could one of you do that?

Done (changed the default branch to `1.1`, updated the branch protection rules to protect `1.?`, and deleted the `master` branch).
