### ISSUE TITLE
Bids: Missing bid.relatedLot

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/ocds-extensions#182]
When giving information about bids, we should be able to specify for which lot the bid was submitted. In line with that, https://extensions.open-contracting.org/en/extensions/lots/master/ says that 

> In other extensions, the following objects can also declare related lots:
> - bids submitted by tenderers (Bid), in the [bid extension](https://github.com/open-contracting-extensions/ocds_bid_extension)

However, looking at https://extensions.open-contracting.org/en/extensions/bids/master/schema/ it seems that `bid` does not have a `bid.relatedLot` field (`bidsStatistic` does).

**Comment by jpmckinney** [comment]
It's added by the Lots extension instead: https://extensions.open-contracting.org/en/extensions/lots/master/schema/#bid
