### ISSUE TITLE
guarantees: Clarify purpose with respect to performance security and tender security

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#184]
Based on the descriptions in https://github.com/open-contracting/standard/issues/651#issuecomment-747765254, my understanding is that:

* Security for the performance of the procurement contract should be modelled using the guarantees extension
* Tender (bid) security should be modelled using the participation fees extension with `.type` set to 'deposit'

I think it would be helpful to add some clarification to the documentation of the guarantees extension to signpost implementers to the participation fees extension for bid security.

**Comment by jpmckinney** [comment]
Great idea! Let's do that.

**Comment by jpmckinney** [comment]
The PR has been opened on the third-party repository, but it's kind of out of our hands. Closing here.
