### ISSUE TITLE
subcontracting: allow subcontractingTerms to be in Lots as in Tender

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#185]
The new UK procurement bill ( https://bills.parliament.uk/bills/3159 ) says that buyers may require suppliers to subcontract part of a contract to another supplier. As this can be per contract there's a need for subcontracting terms at the lot level.

**Comment by duncandewhurst** [comment]
The relevant part of the bill is [section 25](https://publications.parliament.uk/pa/bills/lbill/58-03/004/5803004_en_3.html#pt3-ch2-pb1-l1g25) subsection (2):

> **25 Sub-contracting specifications**
> 
> (1) Subsection [(2)](https://publications.parliament.uk/pa/bills/lbill/58-03/004/5803004_en_3.html#pt3-ch2-pb1-l1g25-l1p1-l2p2) applies if a contracting authority considers that the authority could award a contract for the supply of certain goods, services or works to a particular supplier under section [40](https://publications.parliament.uk/pa/bills/lbill/58-03/004/5803004_en_4.html#pt3-ch3-l1g40) (direct award in special cases).
> 
> (2) In awarding a contract that is wholly or partly for the supply of those goods, services or works under section [18](https://publications.parliament.uk/pa/bills/lbill/58-03/004/5803004_en_3.html#pt3-ch2-pb1-l1g18) (award following competitive procedure), the contracting authority may require that a supplier sub-contracts the supply of those goods, services or works to the particular supplier.
