### ISSUE TITLE
Location: Update title and description to support locations other than delivery locations

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#187]
`Location` is already used for other types of location, e.g. https://extensions.open-contracting.org/en/extensions/bidOpening/master/.

From @jpmckinney via [Slack](https://opencontractingint.slack.com/archives/C03S8JL100P/p1659983887356219?thread_ts=1659922585.006359&cid=C03S8JL100P):

> Hmm, well Location probably needs to be rewritten anyway, as it has a title of “Delivery Location” and a description of “The location where activity related to this tender, contract or license will be delivered, or will take place. A location can be described by either a geometry (point location, line or polygon), or a gazetteer entry, or both.”I think it’s fine for location to leave open the option of being virtual, though for most situations it would be physical (delivery, construction, etc.).

At the same time we can remove the following text which is just repeats the information in the schema:

> A location can be described by either a geometry (point location, line or polygon), or a gazetteer entry, or both.”

**Comment by yolile** [comment]
As part of this, we should also update the [example](https://extensions.open-contracting.org/en/extensions/location/master/#example) to use `deliveryAddresses` instead of `deliveryAddress` and `deliveryLocations` instead of `deliveryLocation`
