### ISSUE TITLE
Beneficial owners: Refer to country codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#189]
OCDS 1.2 adds a country codelist. The `.nationality` field in the beneficial owners extension can be updated to refer to this so that it's values can be validated.

**Comment by duncandewhurst** [comment]
That sounds good to me. You can reuse the wording from [`Address.country`](https://github.com/open-contracting/standard/blob/1052d13206486da5c58fec8d99c2e8cc0604b5a0/schema/release-schema.json#L1844) in `1.2-dev`.

> Is this ready for a PR?

I think so, but I'll defer to @jpmckinney to confirm :-)

**Comment by jpmckinney** [comment]
Closed by above commit. A 1.2 branch can be created when OCDS 1.2 is released #202.
