### ISSUE TITLE
Requirements: Remove/Deprecate 'item' from relatesTo

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#191]
`relatedItem` implies `relatesTo = 'item'`. Similarly, `relatedLots` would imply `relatesTo = 'lot'` (though this code doesn't exist).

`relatesTo` should be reserved for 'tenderer' and 'bid' #110.

If `relatedItem` or `relatedLots` is set and `relatesTo` is also set, that's an incoherence data quality issue.

Requiring publishers to set `relatesTo` when `relatedItem` or `relatedLots` is set is unnecessary and creates an opportunity for inconsistency.

As part of this issue, we can also greatly simplify the description of `relatedItem`:

> Where relatesTo = "item" this field must be populated with the id of the item in this tender section which the criterion relates to. Where relatesTo <> "item" this field should be omitted.

The description of `relatedLots` is much simpler:

> The identifiers of the lots to which this criterion applies.

**Comment by jpmckinney** [comment]
I've now closed #110, so we now actually have the option to eliminate `relatesTo` entirely and instead add a boolean like `relatesToTenderer` (consistent with OCDS) or `relatesToBidder` (consistent with bid extension) or `relatesToSubmitter` (to "future proof" for OCDS 2.0 https://github.com/open-contracting/standard/issues/906).

**Comment by yolile** [comment]
Note that the [responseSource](https://extensions.open-contracting.org/en/extensions/requirements/master/codelists/#responseSource.csv) codelist also uses the code "tenderer", so if we want to be consistent with that field code, we should keep `tenderer`, I guess. (or change that code too)

**Comment by yolile** [comment]
As part of this, we could update the extension documentation that currently says 

> "The extension is designed to allow procuring entities or buyers to express criteria, relating to either items being procured or bidders themselves, as structured data."

, without mentioning lots.

**Comment by jpmckinney** [comment]
Only moldova uses `relatesTo` (similar to #190)

I've changed it to `relatesToTenderer` (matching OCDS).

I've mentioned lots consistent (https://github.com/open-contracting/ocds-extensions/issues/191#issuecomment-1240678661), simplified the description of `relatedItem` (https://github.com/open-contracting/ocds-extensions/issues/191#issue-1365212859), and in general applied the style guide.

https://github.com/open-contracting-extensions/ocds_requirements_extension/commit/54b202f001adfcd2ce6efc5f46aedfd1d3c37189
