### ISSUE TITLE
Techniques: add fee charged to buyer by framework operator

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#194]
The UK is implementing new legislation that will allow framework operators to charge buyers a single fixed percentage fee to use the framework. A new field to include this in OCDS is required. See 38(2) and 44(7) in the [draft bill](https://bills.parliament.uk/bills/3159) for allowable fees for dynamic markets and frameworks respectively.

**Comment by jpmckinney** [comment]
38 Dynamic markets: fees

> (1) Documents establishing a dynamic market other than a utilities dynamic 
market may provide for the charging of fees to suppliers that are awarded a 
contract by reference to their membership of the market.
>
> (2) Fees charged by virtue of subsection (1) must be set as a fixed percentage to be 
applied to the estimated value of the awarded contract.

44 Frameworks

> (7) A framework may provide for the charging of fees at a fixed percentage of the 
estimated value of any contract awarded to the supplier in accordance with the 
framework.

These are about fees/charges to the winner/awardee. However, CRM-8370 had "We need to record the fee that the framework operator will charge the buyer to use the framework, as a percentage". I'll ask for clarification.

**Comment by jpmckinney** [comment]
After clarification, this can be resolved in #81
