### ISSUE TITLE
Location: update examples

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#195]
The examples given in the [Location extension Documentation page](https://extensions.open-contracting.org/en/extensions/location/master/#example) currently use `deliveryAddress` and `deliveryLocation` both of which have been deprecated in favour of `deliveryAddresses` and `deliveryLocations`.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting-extensions/ocds_location_extension/commit/33556c269825082b9de1ff50dccb2c2b1ab1b43b
