### ISSUE TITLE
awardCriteria: update to enable reuse in selectionCriteria extension

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#199]
The new EU eForms mean we need to update selectionCriteria to include an object similar to `awardCriterion` with very similar codelists `criterionThreshold.csv` and `criterionWeight.csv`. To reflect this new use we should:
* rename `AwardCriterionNumber` to `CriterionNumber`
* update descriptions in `criterionThreshold.csv` to cover requests to participate in addition to bids.

**Comment by jpmckinney** [comment]
Sounds good to me!

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting-extensions/ocds_awardCriteria_extension/pull/5#pullrequestreview-1468440390
