### ISSUE TITLE
Simple identifier extension: Remove Tender.identifiers and Contract.identifiers?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#201]
@jpmckinney should the [simple identifier extension](https://github.com/open-contracting-extensions/ocds_simpleIdentifier_extension) contain only the `SimpleIdentifier` definition with `Tender.identifiers` and `Contract.identifiers` remaining in the [OCDS 1.2 draft extension](https://github.com/open-contracting-extensions/ocds_1_2_draft_extension)?

**Comment by jpmckinney** [comment]
Does eForms use the new fields? If so, better to leave them in a separate extension (and maybe rename it accordingly).

**Comment by duncandewhurst** [comment]
Yep, eForms uses those fields for BT-22-Procedure (Internal Identifier) and BT-150-Contract (Contract Identifier), respectively.

To be clear on your proposal - `Tender.identifiers` and `Contract.identifiers` should remain in the simple identifier extension and we should rename it to something like 'Tender and Contract Identifiers'?

**Comment by jpmckinney** [comment]
That sounds simplest to me.

I had to copy SimpleIdentifier to the Lots extension anyway, because the DRT and extension mechanism more generally doesn't specify to follow dependencies (i.e. the `dependencies` field is more like documentation than executable code).

**Comment by duncandewhurst** [comment]
Sounds good. As with the exclusion grounds extension, I've renamed and archived the [fork](https://github.com/open-contracting-extensions/ocds_simpleIdentifier_extension_old) and created a [new repository](https://github.com/open-contracting-extensions/ocds_tender_contract_identifiers_extension) with the new name. I don't have permission to delete the fork.

**Comment by duncandewhurst** [comment]
> I had to copy SimpleIdentifier to the Lots extension anyway, because the DRT and extension mechanism more generally doesn't specify to follow dependencies (i.e. the `dependencies` field is more like documentation than executable code).

Should I copy the SimpleIdentifier definition into the lots extension, then?

**Comment by yolile** [comment]
> Should I copy the SimpleIdentifier definition into the lots extension, then?

Thanks, Duncan, thas was done already https://github.com/open-contracting-extensions/ocds_lots_extension/pull/42  :)

**Comment by jpmckinney** [comment]
Thanks! I've deleted the two old repos. I think this issue is closed now.
