### ISSUE TITLE
Bids: the minLength constraint is specified in the schema for the countriesOfOrigin array

### ISSUE THREAD

**Issue by gusev-aa** [open-contracting/ocds-extensions#204]
[Bid release-schema](https://raw.githubusercontent.com/open-contracting-extensions/ocds_bid_extension/master/release-schema.json)

The minLength constraint is specified in the schema for the countriesOfOrigin array, in other cases minItems is used to constrain the array. I think minItems should be specified there instead of minLength.

**Comment by jpmckinney** [comment]
Thank you for reporting! This is now fixed.
