### ISSUE TITLE
Finance: Clarify semantics, add field for results-based financing

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#207]
While looking at the finance extension for https://github.com/open-contracting/ocds-extensions/issues/206, I noticed a few things that I think could be improved:

1. The extension doesn't really define what financing is.
1. The [finance category codelist](https://extensions.open-contracting.org/en/extensions/finance/master/codelists/#financeCategory.csv) mixes several concepts (asset class, instrument, repayment priority), but with incomplete coverage of each concept, e.g. no code for bonds (instrument), no code for junior debt (repayment priority).
1. I'm not sure that 'guarantee' belongs in the finance category codelist since guarantees are instruments for mitigating risk rather than raising money
1. The [finance type codelist](https://extensions.open-contracting.org/en/extensions/finance/master/codelists/#financeType.csv) is mostly about what type of organization provides the financing, but 'publicBondIssue' and 'supplierCredit' also describe the instrument

I think that we could resolve some of the semantic lack of clarity by:

1. Defining what financing is, perhaps reusing the [PPP FISCAL RISK ASSESSMENT MODEL](https://www.imf.org/external/np/fad/publicinvestment/pdf/PFRAM2.pdf)'s definition of "raising money upfront"
2. Deprecate `financeCategory` and replace it with separate codelists for asset class, instrument type and repayment priority, based on the OECD's [Taxonomy of instruments for infrastructure financing](https://www.oecd.org/finance/private-pensions/Infrastructure-Financing-Instruments-and-Incentives.pdf):
  i. Asset class: Debt, Mixed, Equity
  ii. Instrument: Bonds, Loans, Hybrid, Listed Shares, Unlisted Shares
  iii. Repayment priority: Senior, Subordinated, Junior
4. Model guarantees separately from financing
3. Deprecate `financeType` and replace it with a financing party type codelist (institutional, commercial, bilateral, multilateral, supplier)

With those changes, most of the deprecated codes map directly to their replacements in the new codelists, with the exception of the following slightly more complex mappings:

financeCategory | financeType | assetClass | instrument | priority | financingPartyType | Notes
-- | -- | -- | -- | -- | -- | --
seniorDebt |   | debt |   | senior |   |  
mezzanineDebt |   | mixed |   | subordinated |   | See [Mezzanine Debt (Investopedia)](https://www.investopedia.com/terms/m/mezzaninedebt.asp)
  | publicBondIssue | debt | bond |   |   |  
  | supplierCredit | debt or equity |   |   | supplier | See [Vendor Finance in Infrastructure Projects (Management Study Guide)](https://www.managementstudyguide.com/vendor-finance-in-infrastructure-projects.htm)

Edit: Noting another useful taxonomy: https://cdn.gihub.org/umbraco/media/3713/gi-hub-innovative-funding-and-financing-framework.pdf

**Comment by jpmckinney** [comment]
In general, it makes sense to deprecate and split those codes / codelists.

1. In what scenario is 'supplierCredit' equity? 
1. Where is 'grant' moving? I assume `instrument`, with no value for other fields.
1. Is "debt" typically described as an "asset class"? If not, we should find another name for the codelist.
1. Is priority applicable for anything other than debt? If not, we should rename it `repaymentPriority` to avoid ambiguity.
1. Is "financingPartyType" clear? There are at least two parties in any financing arrangement. A supplier can issue bonds to raise capital (in which case the supplier owes the value plus interest to their buyers). A bank can issue a loan to a supplier (again, in which case the supplier owes the value plus interest to the bank). A supplier can issue shares to raise capital (in which case the supplier might not owe anything, unless the shares pay dividends - they just give a share of ownership / control to buyers). In all cases, we know it's the supplier raising capital. So, it should never be set to 'supplier'. I think maybe we just add an organization classification to the organization referenced by `financingParty`?

**Comment by duncandewhurst** [comment]
1. From [Vendor Financing (Investopedia)](https://www.investopedia.com/terms/v/vendorfinancing.asp):

> Vendor financing can be structured with either debt or equity instruments... With equity vendor financing, the vendor can provide goods in exchange for an agreed-upon amount of company stock. 

The Management Study Guide that I linked in the issue description suggests that equity vendor financing is unusual in the context of infrastructure projects, but not unheard of:

> Theoretically, vendor finance can be debt-based or equity-based. However, the reality is that very few vendors ever choose the equity model. About 95% of vendor finance is provided through the debt-based model.

2. Where is 'grant' moving? I assume instrument, with no value for other fields.

That's correct, it was an unintentional omission.

3. If so, is a grant a financial instrument? Maybe we need to change the field name to vehicle, type or something.

There is some debate about where government grants are financial instruments ([example](https://www.ifrs.org/content/dam/ifrs/meetings/2019/march/eeg/ap8-ias-20-government-grant-receivables.pdf) - slide 6 onwards), but grants are commonly grouped with other financial instruments when looking at project financing ([GCF example](https://www.greenclimate.fund/project/fp209#investment)) so I had thought it OK to include in the list of instruments.

That said, the GCF example above also groups guarantees with grants and financial instruments when looking at project financing. However, I don't understand how it makes sense to sum up guarantees, like a minimum revenue guarantee which only takes effect if the project revenues are lower than forecast, with grants and loans which are about raising money to deliver a project... so perhaps I need to learn more about guarantees in project financing.

4. Is "debt" typically described as an "asset class"? If not, we should find another name for the field.
    Seems it's okay: https://www.investopedia.com/terms/f/financialinstrument.asp

The OECD taxonomy uses 'fixed income' but I figured that term is more relevant from the perspective of a lender than it is from the perspective of the borrower (i.e. the project company).

5. Is priority applicable for anything other than debt? If not, we should rename it repaymentPriority to avoid ambiguity.

It's also applicable to hybrid instruments, like mezzanine financing, which are a combination of debt and equity. However, in that context it presumably only applies to the debt portion of the financing so renaming to repaymentPriority sounds good.

6. Is "financingPartyType" clear? There are at least two parties in any financing arrangement. A supplier can issue bonds to raise capital (in which case the supplier owes the value plus interest to their buyers). A bank can issue a loan to a supplier (again, in which case the supplier owes the value plus interest to the bank). A supplier can issue shares to raise capital (in which case the supplier might not owe anything, unless the shares pay dividends - they just give a share of ownership / control to buyers). In all cases, we know it's the supplier raising capital. So, it should never be set to 'supplier'. I think maybe we just add an organization classification to the organization referenced by financingParty?

'supplier' was intended to model supplier credit arrangements, where the supplier provides goods or services to the project company in exchange for debt or equity, in which case the supplier would be the party providing the finance.

My concern with moving this information to an organisation classification is that the details of the actual organisation might not be known/disclosable, but it might still be desirable to disclose that X amount of financing was from multilateral lenders, Y amount from commercial etc.

**Comment by jpmckinney** [comment]
> supplier credit arrangements

Ah, so the supplier is a third-party supplier, not one of the project proponents, right?

I suppose `financyPartyType` (given we already have `financyParty`) is fine then.

**Comment by duncandewhurst** [comment]
> Ah, so the supplier is a third-party supplier, not one of the project proponents, right?

Yes, but I now realise how confusing that is so I will have a think about an alternative term!

**Comment by duncandewhurst** [comment]
@evelyndinora flagged results-based payments (also known as results-based climate finance and performance-based payments) as a possible instrument type.

Result-based payments are often referred to as a financial instrument, for example in the [financing summary](https://www.greenclimate.fund/project/fp144#investment) for the Costa Rica REDD-plus Results-Based Payments for 2014 and 2015 on the Green Climate Fund website:

![image](https://github.com/open-contracting/ocds-extensions/assets/19265814/75feb74c-66d0-43e1-af55-f803b286ae66)

However, based on my research, I think that a results-based payment is not a financial instrument in the sense that a bonds, loans and shares are financial instruments. Rather, a results-based payment is likely to be executed in the form of a grant, as shown in the [approved funding proposal](https://www.greenclimate.fund/sites/default/files/document/fp144-undp-costa-rica.pdf) (page 77) for the above results-based payment:

![image](https://github.com/open-contracting/ocds-extensions/assets/19265814/b9ab4602-e8e1-4ff7-8b74-bc68c87a906e)

This is backed up by the World Bank's [technical report on results-based aid in the energy sector](https://openknowledge.worldbank.org/server/api/core/bitstreams/c8acf47f-00cb-5cbb-96f4-8fc13fdc20b0/content), according to which:

> The financial instrument used in an RBA can be structured as either a grant or a loan.

The report goes on to discuss the applicability of different financial instruments to results-based aid:

![image](https://github.com/open-contracting/ocds-extensions/assets/19265814/2808f934-6774-44d7-a8fd-159e1e3f336f)

Therefore, rather than modelling results-based payments as a financial instrument, I think that we should add a boolean `Finance.resultsBased` field in order to allow any type of financial instrument to be results-based.

**Comment by jpmckinney** [comment]
Thank you for the research on this! That does sound like the best approach.

**Comment by EvelynDinora** [comment]
Thanks Duncan, I agree with your proposal.

**Comment by duncandewhurst** [comment]
CoST suggested the following classification for financing party type, which we'll need to reconcile with the existing codelist:

* Private 
* Public 
* non-governmental 
* sub-national 
* national 
* regional 
* international 

We might consider splitting into separate fields or classifications since the above list mixes two concepts: high-level sector (private, public, non-governmental) and geographic scope (sub-national, national, regional, international).

@EvelynDinora provided this helpful explanation of the use cases for the classification:

> the interest of the SG is to see which and what type of entity is facilitating the investments in climate finance projects in the country. The experience tells that major entities such multilateral banks are obtaining funds against national entities. The issue is that major entities are extremely burocratic and the transactional costs are higher than the national entities who can speed up the investments at lower costs (again aggregated data is the main interest but this collected project per project).

**Comment by jpmckinney** [comment]
Agree on splitting out geographic scope, etc. These would be classifications on the organization entry in the `parties` array?

**Comment by duncandewhurst** [comment]
Yes, I think that makes sense.

In https://github.com/open-contracting/ocds-extensions/issues/207#issuecomment-1765456721, I was concerned that the details of the actual organisation might not be known/disclosable, but the CoST IDS/OC4IDS review proposes an element for that.

**Comment by duncandewhurst** [comment]
Following up on guarantees and naming of `instrument`:

> 3. Model guarantees separately from financing

> 5\. If so, is a grant a financial instrument? Maybe we need to change the field name to `vehicle`, `type` or something.
> 
> There is some debate about where government grants are financial instruments ([example](https://www.ifrs.org/content/dam/ifrs/meetings/2019/march/eeg/ap8-ias-20-government-grant-receivables.pdf) - slide 6 onwards), but grants are commonly grouped with other financial instruments when looking at project financing ([GCF example](https://www.greenclimate.fund/project/fp209#investment)) so I had thought it OK to include in the list of instruments.
> 
> That said, the GCF example above also groups guarantees with grants and financial instruments when looking at project financing. However, I don't understand how it makes sense to sum up guarantees, like a minimum revenue guarantee which only takes effect if the project revenues are lower than forecast, with grants and loans which are about raising money to deliver a project... so perhaps I need to learn more about guarantees in project financing.

Guarantees play an important role in raising money upfront because they reduce the risks to which lenders are exposed, making it easier for a project to access financing.

Like grants, guarantees are often described as financial instruments ([example](https://commission.europa.eu/funding-tenders/find-funding/financial-instruments-equity-guarantees-and-loans_en)) although the accounting treatment seems to differ depending on the type of guarantee: a debt repayment guarantee is a considered a financial instrument according to [IFRS 9](https://www.xrb.govt.nz/dmsdocument/4316), but some types of guarantee used in PPP projects are not recognized in financial statements ([source](https://www.elibrary.imf.org/display/book/9781589064935/ch002.xml)).

Based on the above, contrary to my original suggestion, I no longer think we should model guarantees separately from financing.

Regarding naming, let's go with `type` since I think we'll find it difficult to write a description for `instrument` that definitely covers both grants and guarantees (the IFRS definition is "any contract that gives rise to a financial asset of one entity and a financial liability or equity instrument of another entity" and my understanding is that this excludes some types of guarantee that create only contingent liabilities).

I still don't understand how it makes sense for the GCF website to sum up guarantees along with other financing arrangements like grants and loans, but users can filter (or not) the `finance` array to suit their needs so I don't think it's a problem to model them all as financing arrangements.

**Comment by jpmckinney** [comment]
Thank you for your research on this! That sounds like the best solution.

**Comment by duncandewhurst** [comment]
# Background

See https://github.com/open-contracting/infrastructure/issues/413 for the relationship to the CoST IDS/OC4IDS review.

# Proposal

## Schema changes

Path | Title | Description | Type (format) | Codelist | Change
-- | -- | -- | -- | -- | --
`Contract.finance` | Finance | ~~An array with details of each source of finance arranged~~ **Information about financing arrangements** for this contract. | Array of `Finance` objects | | Changed
`Budget.finance` | Finance | ~~An array with details of each source of finance planned~~ **Information about financing arrangements** for this ~~procedure~~ **contracting process**. | Array of `Finance` objects | | Changed
`Finance` | Financing arrangement | ~~Information about a financing arrangement.~~ **An arrangement between two parties related to raising money.** | Object | | Changed
~~`financeType`~~ | ~~Finance type~~ | ~~The type of finance arranged.~~ | ~~String~~ | ~~financeType~~ | Deprecated in favour of `Finance.financingPartyType` and `Finance.type`
~~`Finance.financeCategory`~~ | ~~Finance category~~ | ~~The nature of the finance, relevant to determining the order of preference for investors to get their money back in case of liquidation.~~ | ~~String~~ | ~~financeCategory~~ | Deprecated in favour of `Finance.assetClass`, `Finance.type` and `Finance.repaymentPriority`
`Finance.assetClass` | Asset class | The asset class to which this financing arrangement belongs, from the closed [assetClass codelist]() | Array of strings | assetClass | New
`Finance.type` | Type | The type of this financing arrangement, from the closed [financingArragementType codelist]() | String | financingArrangementType | New
`Finance.repaymentPriority` | Repayment priority | The priority in which the debt element of this financing arrangement will be repaid in the event of bankruptcy, from the open [debtRepaymentPriority codelist]() | String | debtRepaymentPriority | New
`Finance.financingPartyType` | Financing organization type | The type of the financing organization, from the closed [financingPartyType codelist]() | String | financingPartyType | New
`Finance.resultsBased` | Results based | Whether payments under this financing arragement are contingent on the achievement of pre-defined results. | Boolean | | New

## Codelist changes

### financeType (deprecated)

Code | Title | Description | Source | Deprecation description
-- | -- | -- | -- | --
institutional |	Institutional | This finance was provided by institutional investors: organizations that pool money to purchase securities, real property, and other investment assets or originate loans. Institutional investors include banks, insurance companies, pensions, hedge funds, REITs, investment advisors, endowments, and mutual funds. | https://en.wikipedia.org/w/index.php?title=Institutional_investor&oldid=764994591 | Deprecated in favour of 'institutional' in the financingPartyType codelist
commercial | Commercial | This finance was provided by private parties who do not fall within the definition of institutional investor. | | Deprecated in favour of 'commercial' in the financingPartyType codelist
bilateral |	Bilateral | This finance was provided by a bilateral institution: an agency of one specific government, usually a development agency or export-credit agency with a mandate to support domestic businesses in pursuing investments abroad. | https://ppi.worldbank.org/methodology/glossary | Deprecated in favour of 'bilateral' in the financingPartyType codelist
multilateral | Multilateral | This finance was provided by a multilateral institution: a body created by a group of countries to provides financing and professional support, primarily for the purpose of development. |  | Deprecated in favour of 'multilateral' in the financingPartyType codelist
publicBondIssue |	Public bond issue | This finance was provided through a public bond issue. | | Deprecated in favour of 'debt' and 'bond' in the assetClass and financingArrangementType codelists, respectively.
supplierCredit | Supplier credit | This finance was provided through a line of credit provided by a supplier. | | Deprecated in favour of 'vendor' in the financingPartyType codelist
other |	Other | This finance was provided through some other source. | | Deprecated in favour of 'other' in the financingPartyType codelist

### financingPartyType (new)

Code | Title | Description | Source | Change
-- | -- | -- | -- | --
institutional |	Institutional | This finance was provided by institutional investors: organizations that pool money to purchase securities, real property, and other investment assets or originate loans. Institutional investors include banks, insurance companies, pensions, hedge funds, REITs, investment advisors, endowments, and mutual funds. | https://en.wikipedia.org/w/index.php?title=Institutional_investor&oldid=764994591 | No change - copied from financeType codelist
commercial | Commercial | This finance was provided by private parties who do not fall within the definition of institutional investor. | | No change - copied from financeType codelist
bilateral |	Bilateral | This finance was provided by a bilateral institution: an agency of one specific government, usually a development agency or export-credit agency with a mandate to support domestic businesses in pursuing investments abroad. | https://ppi.worldbank.org/methodology/glossary | No change - copied from financeType codelist
multilateral | Multilateral | This finance was provided by a multilateral institution: a body created by a group of countries to provides financing and professional support, primarily for the purpose of development. |  | No change - copied from financeType codelist
vendor | Vendor | This finance was provided through a line of credit provided by a vendor. | | Adapted from 'supplierCredit' in financeType codelist
other |	Other | This finance was provided through some other source. | | No change - copied from financeType codelist

### financeCategory (deprecated)

Code | Title | Description | Deprecation description
-- | -- | -- | --
equity | Equity | Equity finance is given in exchange for a share of ownership in the project (usually via direct or indirect shareholding in a Special Purpose Vehicle (SPV) company created to run the project). | Deprecated in favour of 'equity' in the assetClass codelist
seniorDebt | Senior debt | Senior debt (sometimes called senior loans) take priority over other more junior debt. | Deprecated in favour of 'debt' in the assetClass codelist and 'senior' in the debtRepaymentPriority codelist
mezzanineDebt |	Mezzanine debt 	| Mezzanine debt (sometimes called mezzanine loans) take priority over common shares. | Deprecated in favour of 'debt' and 'equity' in the assetClass codelist and 'subordinated' in the debtRepaymentPriority codelist
grant |	Grant | A grant is finance provided without expectation of repayment. | Deprecated in favour of 'grant' in the financingArrangementType codelist
guarantee | Guarantee | A guarantee is a promise by one party to assume the debt of another if the other defaults. Guarantees are not to be counted in totals of the overall financing of a project. | Deprecated in favour of 'guarantee' in the financingArrangementType codelist
other |	Other debts or investments | Any details of the conditions attached to this finance can be provided in the notes field. | Deprecated in favour of the assetClass, financingArrangementType and debtRepaymentPriority codelists

### assetClass (new)

Code | Title | Description
-- | -- | --
debt | Debt | A contract that obliges a borrower to repay a lender in accordance with a specified maturity and under specified terms. Also known as fixed income.
equity | Equity | A contract that acts as legally recognised evidence of ownership rights in an enterprise.

Notes:
* I omitted the proposed 'mixed' code in favour of making `Finance.assetClass` an array.

### financingArrangementType (new)

Code | Title | Description
-- | -- | --
bond | Bond | A debt-based financial instrument issued by a national government, sub-national government, project company or corporate entity. A bond typically obliges the issuer to make interest payments (coupons) over a specified period and to repay the principle (amount borrowed) at the maturity date.
loan | Loan | A debt-based financial instrument provided by a lender such as a commercial bank, a multi-lateral financial institution, or development agency. A loan typically obliges the borrower to make principle and interest payments over a specified period.
hybrid | Hybrid | A debt-based instrument with equity-like participation. Also called mezzanine finance.
shares.listed | Listed shares | An equity instrument representing ownership rights in a publicly traded company. Also called stocks.
shares.unlisted | Unlisted shares | An equity instrument representing ownership rights in a private company.
grant | Grant | Money provided without expectation of repayment.
guarantee | Guarantee | A promise by one party to assume the debt of another if the other defaults.

## debtRepaymentPriority (new)

Code | Title | Description
-- | -- | --
senior | Senior | Debt that must be repaid before subordinated debt.
subordinated | Subordinated | Debt that must be repaid only after senior debt is repaid.

Notes:

* The following diagram ([source](https://corporatefinanceinstitute.com/resources/commercial-lending/junior-debt/)) suggests that this could be broken down further, but 'senior' and 'subordinated' seem like the main terms.

![image](https://github.com/open-contracting/ocds-extensions/assets/19265814/532c50ef-1050-4eb8-861e-3a51f3a13511)

# Example

```json
{
  "planning": {
    "budget": {
      "finance": [
        {
          "id": "1",
          "financingParty": {
            "id": "1",
            "name": "Development Bank of South Africa"
          },
          "financingPartyType": "bilateral",
          "assetClass": ["debt"],
          "type": "loan",
          "repaymentPriority": "senior",
          "resultsBased": false
        }
      ]
    }
  }
}
```

# Sources

* [IFRS 9: Financial instruments - Grant Thornton (page 2)](https://www.grantthornton.nl/globalassets/1.-member-firms/netherlands/documenten/flyers-pdf/2018/ifrs-9-financial-instruments-grant-thornton-eng.pdf): assetClass codelists - 'debt' and 'equity' code descriptions.
* [Infrastructure Financing Instruments and Incentives - OECD](https://www.oecd.org/finance/private-pensions/Infrastructure-Financing-Instruments-and-Incentives.pdf): financingArrangementType code descriptions
* [Bond (finance) - Wikipedia](https://en.wikipedia.org/wiki/Bond_(finance)): financingArrangementType codelist - 'bond' code description
* [Loan - Wikipedia](https://en.wikipedia.org/wiki/Loan): financingArrangementType codelist - 'loan' code description
* [Junior Debt - Corporate Finance Institute](https://corporatefinanceinstitute.com/resources/commercial-lending/junior-debt/) - debtRepaymentPriorty codelist descriptions


cc @evelyndinora @mgraca-prado

**Comment by jpmckinney** [comment]
financingArragementType -> financingArrangementType

Bonds can be public or private. I don't know if the distinction is relevant (yet), so I'm fine with just 'bond'. If we later have a use case for distinguishing the two, we can add sub-codes.

**Comment by duncandewhurst** [comment]
Thanks! I've corrected the typo. I take it that you're happy with the rest of the proposal so I'll move this to agreed. Let me know if not.

**Comment by jpmckinney** [comment]
Yes, looks good – I didn't spend much time looking at descriptions, but I didn't notice anything to comment on.
