### ISSUE TITLE
Finance: Add field to identify the funding source

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#209]
## Background

CoST's proposed climate finance data points distinguish between:

* The funding source, e.g. the Green Climate Fund (GCF) or the Global Environment Facility (GEF)
* The entity through which the finance is accessed, e.g. an [accredited entity](https://www.greenclimate.fund/about/partners/ae#), such as the African Development Bank, for GCF-funded projects; or a [GEF agency](https://www.thegef.org/partners/gef-agencies), such as the UN Development Programme, for GEF-funded projects

### GCF research

The financial flows section (page 55 onwards) of the [approved funding proposal](https://www.greenclimate.fund/sites/default/files/document/fp209-dbsa.pdf) for the Climate Change Resilience through South Africa’s Water Reuse Programme GCF project provides a helpful diagram that shows how funds flow from the GCF, through the accredited entity (DBSA - the Development Bank of South Africa) to individual infrastructure projects (Project SPV 1 etc.):

![image](https://github.com/open-contracting/ocds-extensions/assets/19265814/d8ec76d5-ea5f-4219-945d-96c34ad8902b)

The same document clearly states that the GCF does not directly fund the individual infrastructure projects:

> The GCF does not directly finance the underlying water reuse sub-projects. The GCF provides loans (at a Programme Level) to the Accredited Entity (the DBSA), who facilitates the GCF Concessional loan(s) into the underlying sub-projects, as required

### GEF research

Looking at the [approved funding request](https://publicpartnershipdata.azureedge.net/gef/PMISGEFDocuments/Climate%20Change/Morocco%20-%20%289567%29%20-%20Renewable%20Energy%20for%20the%20City%20of%20Marrakech%E2%80%99s%20Bus%20R/ID9567_Council_Notification_Letter.pdf) for the Renewable Energy for the City of Marrakech’s Bus Rapid Transit System GEF project, the GEF seems to operate a similar model with an added complexity: the ultimate funding source can be one of several [GEF funds](https://www.thegef.org/who-we-are/funding), which are labelled as 'funding sources' in the [GEF project database](https://www.thegef.org/projects-operations/database). In the example above, the UNDP provides a grant to the infrastructure project that is ultimately funded by the (main) GEF Trust Fund.
 
## Proposal

I think that the entity through which finance is accessed belongs in `financingParty` ("The organization providing this financing arrangement.") so I propose adding the following field to model the funding source:

Path | Title | Description | Type | 
-- | -- | -- | --
`Finance.source` | Funding source | The source of funds for this financing arrangement. For example, the Green Climate Fund. | string

## Examples

The following example is based on the above diagram and shows how a concessional, subordinated, GCF-funded loan from the DBSA would be represented, taking into account the changes proposed in #207.

```json
{
  "budget": {
    "finance": [
      {
        "id": "1",
        "assetClass": "debt",
        "instrument": "loan",
        "repaymentPriority": "subordinated",
        "concessional": true,
        "resultsBased": false,
        "financingParty": {
          "id": "1",
          "name": "Development Bank of South Africa"
        },
        "value": {
          "amount": 50000000,
          "currency": "ZAR"
        },
        "source": "Green Climate Fund"
      }
    ]
  }
}
```

The following example is based on the GEF project linked in the research above and shows how a GEF-funded grant from UNDP would be represented:

```json
{
  "budget": {
    "finance": [
      {
        "id": "1",
        "instrument": "grant",
        "financingParty": {
          "id": "1",
          "name": "United States Development Programme"
        },
        "value": {
          "amount": 1319863,
          "currency": "USD"
        },
        "source": "GEF Trust Fund"
      }
    ]
  }
}
```
cc @evelyndinora, @odscjen

**Comment by jpmckinney** [comment]
In the eForms and EU OCDS profiles, we mapped this to `description` (which was otherwise unoccupied). I suppose this issue is motivated by a need for a narrower field for this concept.

I spent a bit of time thinking of alternative names ("fund" would work for GCF and GEF). I don't know what other "sources" we might expect. `source` sounds fine to me.

**Comment by duncandewhurst** [comment]
@evelyndinora, @mgraca-prado, are you happy with this proposal?

**Comment by EvelynDinora** [comment]
Sounds good to me. Besides the GCF and GEF we can expect other regional funds too like the [Africa Climate Change Fund](https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/africa-climate-change-fund), but all of them are called "fund"
