### ISSUE TITLE
Finance: Terms

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#210]
# Background

The CoST IDS/OC4IDS review proposes the following data point:

**Module:** Climate finance
**Indicator:** Economic viability
**Data point:** Terms of climate finance (Preparation)
**Disclosure format:**

> This includes several financial terms:
> * Maturity (years)
> * Grace period (years)
> * annual principal repayment years (% of initial principle)
> * Interest (%)
> * Service fee (per annum)
> * Commitment fee (per annum)

The following terms are already covered by existing fields in the finance extension:

* Maturity (years): `Finance.period`
* Interest (%): `Finance.interestRate`

Looking at the [GCF loan terms](https://www.greenclimate.fund/sites/default/files/document/financial-terms-conditions-grants-loans.pdf), I think that the following terms are too complicated to model as structured data due to the potential for different loan lengths, loan structures and fee structures. Therefore, I would map these as unstructured data to `Finance.description`:

* annual principal repayment years (% of initial principle)
* Service fee (per annum)
* Commitment fee (per annum)

# Proposal

For the grace period, I propose adding a `Finance.repaymentPeriod` field, the grace period can then be calculated as the difference between `Finance.period` (the maturity) and `Finance.repaymentPeriod`.

cc @evelyndinora @mgraca-prado @odscjen

**Comment by duncandewhurst** [comment]
@evelyndinora, @mcgraca-prado, @jpmckinney are you happy with this proposal?

**Comment by jpmckinney** [comment]
👍

**Comment by EvelynDinora** [comment]
Yes! many thanks @duncandewhurst
