### ISSUE TITLE
Finance: Re-order fields in logical order

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#211]
> We can maybe open a new issue about putting all these fields in a logical order.

https://github.com/open-contracting-extensions/ocds_finance_extension/pull/26#pullrequestreview-1730988711

**Comment by duncandewhurst** [comment]
@jpmckinney let me know what you think of the following ordering:

- 'General' metadata:
  - `id`
  - `title`
  - `description`
  - `value`
- 'Type' data
  - `assetClass`
  - `type`
  - `repaymentPriority`
  - `concessional`
  - `resultsBased`
- Organizational data
  - `financingParty`
  - `financingPartyType`
  - `source`
- Time-based data
  - `period`
  - `paymentPeriod`
  - `paymentFrequency`
- 'Commercial' data
  - `interestRate`
  - `exchangeRateGuarantee`
  - `stepInrights`
- Cross references: 
  - `relatedLots`

**Comment by jpmckinney** [comment]
I think Organizational before Type, that way everything that follows is more about the instrument.

Rest is good!
