### ISSUE TITLE
Lots: Add electronicSubmissionPolicy

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#212]
OCDS 1.2 now has /tender/submissionTerms/electronicSubmissionPolicy https://github.com/open-contracting/standard/issues/1183

Since Lots is versioned with OCDS, it makes sense for /tender/lots[]/submissionTerms/electronicSubmissionPolicy to be defined by the Lots extension, instead of the electronicSubmissionPolicy extension.

As discussed in the above issue, we can leave electronicSubmissionPolicy in Submission Terms, to avoid having to maintain a 1.1 and 1.2 version of that extension. The only consequence is that the submission terms extension can overwrite the field, but since we control that extension, we can keep it in sync.

**Comment by odscjen** [comment]
When adding this to `Lots` should the full field be copied or can a `$ref` be used to point to the definition in the 1.2 version of the core?

**Comment by odscjen** [comment]
Fixed by https://github.com/open-contracting-extensions/ocds_lots_extension/pull/47 so closing now
