### ISSUE TITLE
PPPs: update descriptions of percentage fields

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#214]
Follow on from https://github.com/open-contracting-extensions/ocds_participationFee_extension/pull/27#discussion_r1412574442

Update, `riskPremium`, `discountRate`, `debtEquityRatio`, `subsidyRatio` and `projectIRR` descriptions to include ", expressed as a decimal (for example, 0.1) and not as a percentage (for example, 10)." to ppp. Also remove "Further details..." sentences from these descriptions.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting-extensions/ocds_ppp_extension/commit/d559d143d29589deaea2cf8e6c0fef45b1ac9711
