### ISSUE TITLE
selectionCriteria: methodology(s) used to assess submissions against stated conditions/criteria

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#218]
For their new Dynamic Markets the UK will need to record "the methods that the procuring entity will use to verify that a supplier satisfies the conditions".

The conditions themselves can be recorded using the `selectionCriteria` extension, but there is currently nowhere in that for a field to record how the procuring entity will be judging how/if the submissions meet the criteria.

This could be solved with the inclusion of a new field free-text, perhaps `.criteria.assessmentMethodology`, putting it in `criteria` as the assessment methodology could vary per criterion. 

Are there any other jurisdictions that need to record similar data? It doesn't look as though the new EU eForms will require it.

**Comment by jpmckinney** [comment]
In TED this was "Methods according to which each of those conditions will be verified" `/LEFTI/QUALIFICATION/METHODS`, mapped as "Add to the tender.otherRequirements.qualificationSystemMethods array"

https://standard.open-contracting.org/profiles/eu/latest/en/forms/F07/#III.1.9

I don't know if/where this is in eForms.

**Comment by odscjen** [comment]
that TED field only appears in F07 and it's mapped field, `otherRequirements.qualificationSystemMethods`, isn't being used in the eForms to OCDS mapping. The TED XPATH isn't in our guidance mapping either. 

F07 appears to have become eForms sub-type 15 "Notice on the existence of a qualification system – sectoral directive" but I can't find anywhere that specifies the fields that need to go into this sub-type to see if they've kept something similar to `/LEFTI/QUALIFICATION/METHODS`. It looks as though they may have gotten rid of it in eForms?

**Comment by jpmckinney** [comment]
That’s possible. I’d have to check the legislation to see how/whether this field was described there. Anyhow, for the UK, we have this existing field we can use.

**Comment by jpmckinney** [comment]
Closing as no changes need to be made.

**Comment by Ben-Hickling** [comment]
@jpmckinney - The new UK notices will allow multiple conditions for membership in different selectionCriteria.criteria.description - at least two because we will separate economic and technical conditions. If we use the string array otherRequirements.qualificationSystemMethods for the verification methods for those conditions then I'm not sure how we would relate them to the right criteria element. A new element in criteria would keep the related fields in the same parent with no need for cross-referencing.

**Comment by jpmckinney** [comment]
@Ben-Hickling Ah, yes, with that context, I agree it would be best to pair the verification methods with the criteria. Maybe `verificationMethod`?

**Comment by Ben-Hickling** [comment]
Thanks, I'm happy with `verificationMethod` if that's the preferred name.

**Comment by odscjen** [comment]
@Ben-Hickling is this field going to be needed at the `tender` level or will it only be used for individual `lots`?
