### ISSUE TITLE
coveredBy: new code for Comprehensive and Progressive Agreement for Trans-Pacific Partnership

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#223]
The UK are using the [coveredBy](https://extensions.open-contracting.org/en/extensions/coveredBy) extension and need to add a code to the 'coveredBy' codelist to cover the Comprehensive and Progressive Agreement for Trans-Pacific Partnership.

Have suggested they create a local extension, and use the code 'CPTPP'.

Other countries that are signed up to this agreement and therefore may need this code include:
* Mexico
* Australia
* New Zealand
* Canada
* Brunei
* Chile
* Japan
* Malaysia
* Peru
* Singapore
* Vietnam

I think it's a possible contender for adding to the extension itself.

**Comment by jpmckinney** [comment]
Yes, okay to add. Current list: https://extensions.open-contracting.org/en/extensions/coveredBy/master/codelists/
