### ISSUE TITLE
Lots: Replace Lot.status with Lot.finalStatus

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#224]
From https://github.com/open-contracting/standard/pull/1648#issuecomment-1967611282:

> > I noticed that docs/examples/unsuccessful_tender/tender.json has lots.status = 'unsuccessful' - should the lot extension also be updated following the same logic as the changes to tender?
> 
> Yes, please create an issue.

* ~~Update `docs/examples/unsuccessful_tender/tender.json` in the standard.~~ Edit (James): I had added this in March, but looking at it now, I don't think an update is needed (or we did it already). On that page, `tenderUpdate.json` sets `"finalStatus": "unsuccessful"`.

**Comment by odscjen** [comment]
@jpmckinney the README of the lots extension contains a section entitled "[How to set `tender.status` if lots' statuses differ](https://extensions.open-contracting.org/en/extensions/lots/master/#how-to-set-tender-status-if-lots-statuses-differ)?" In 1.2 this field (`tender.status`) is being deprecated. As we don't have a 1.2 branch for the lot extension I don't think we should update this section to refer to a field that currently only exists in the unpublished 1.2 core schema. Should I instead add a section on "How to set `tender.finalStatus` if lots' statuses differ?" and note that this is only relevant to publishers using OCDS 1.2?

**Comment by jpmckinney** [comment]
Let's create a PR, and then add the task of merging it to https://github.com/open-contracting/ocds-extensions/issues/202 Once the PR is approved, we can close this issue to leave only #202 open.

**Comment by jpmckinney** [comment]
And in the PR, edit the section to refer to finalStatus (with corresponding edits).
