### ISSUE TITLE
Options and Renewals: describes what *will* happen in a contract but only at the tender stage?

### ISSUE THREAD

**Issue by odscjen** [open-contracting/ocds-extensions#226]
Both options and renewals talk about the contracts that will result from the contracting process and imply that the option or renewal described *will* be a part of the contract.

`hasOptions` = "Whether or not the buyer reserves the right to make additional purchases from the supplier, as long as the contract is valid."
`hasRenewal` = "Whether the contracts can be renewed."

But they are only applicable at the `tender` stage, i.e. before an award has been made never mind a contract negotiated.

There is the potential for a buyer to decide when it comes to drawing up the contract with the award supplier(s) that actually they won't need to exercise the option or renewal and so not include it in the contract. At this point the information in `tender.hasOptions` or `tender.hasRenewal` becomes incorrect. e.g. `.hasRenewal` set to `true` but no renewal is included in the final contract.

Should these extension instead be about elements that the buyer *may* include in the contract? i.e.

`hasOptions` - "Whether or not the buyer may reserve the right to make additional purchases from the supplier, as long as a contract that results from the contracting process is valid"

`hasRenewal` - "Whether the buyer may reserve the right to renew a contract that results from the contracting process."

Looking at the WTO GPA article it talks about "the possibility of options" which I'm interpreting to mean that the options are just a possibility, not that they will definitely be included in the final contracts? (see [GPA Article 2 para 6](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm#articleVII)). 

> In estimating the value of a procurement for the purpose of ascertaining whether it is a covered procurement the procuring entity shall include the estimated maximum total value of the procurement over its entire duration...taking into account all forms of remuneration, including ... where the procurement provides for the possibility of options, the total value of such options.

Looking at the EU eForms [guidance](https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#extensionsSection) it discussed things that "may" occur. The example given in the definition of BT-58 is (emphasis mine)
> For example, a contract may be valid for one year and the buyer *may* keep a possibility to renew it (e.g. once, twice) for another three months, if he is content with the services he received.

which implies to me that the resulting contract may also *not* include a possibility of renewal.

If this change would be made there may then be a need to include the information about what options or renewals the contract *does* contain in `contracts`.

New UK legislation will require details of the options and renewals to be included in Contract notices and not just in tender notices with the possibility that the potential options or renewals open to the buyer at the tender stage may not be exercised in the contracts.

I couldn't find any discussion previously about this semantic nitpicking!

**Comment by jpmckinney** [comment]
That languages comes from the eForms regulation annex:

> The buyer **reserves the right** (not an obligation) **for additional purchases from the contractor** (while the contract is valid).

> ... By renewing, the buyer **reserves the right** (i.e. not an obligation) **to renew the contract** (i.e. extend its duration) without a new procurement procedure. For example, a contract may be valid for one year and the buyer may keep a possibility to renew it (e.g. once, twice) for another three months, if he is content with the services he received.

We can reword to (we don't use "may" as this is not normative with respect to the data):

> Whether the buyer is expected to reserve the right for additional purchases from the supplier.

> Whether the buyer is expected to reserve the right to renew the future contract(s).

We can then add similar fields to either award or contract (whichever is most correct for UK), changing "is expected to reserve" to "reserves".

**Comment by odscjen** [comment]
That's better wording than I had suggested :)

The UK needs both award and contract (options will need to be detailed at the award level for private utilities see [regulation 28](https://www.legislation.gov.uk/ukdsi/2024/9780348259728/regulation/28) and at contract level for all other open and competitive flexible procedures, see [regulation 32](https://www.legislation.gov.uk/ukdsi/2024/9780348259728/regulation/32).)

In the Options extension the current wording of `Options` works for all stages as does `Renewal` in the Renewal extension so we can reuse those objects at `award` and `contract`.

So the new fields will need to be equivalents for `hasOptions` and `hasRenewal`. I think the following works:

Options extension
field | description
-- | --
`tender.hasOptions` | Whether the buyer is expected to reserve the right for additional purchases from the supplier.
`Award.hasOptions` | Whether the buyer is expected to reserve the right for additional purchases from the supplier.
`Award.options` | A description of the options
`Contract.hasOptions` | Whether the buyer reserves the right for additional purchases from the supplier, as long as the contract is valid.
`Contract.options` | A description of the options

Renewals extension
field | description
-- | --
`tender.hasRenewal` | Whether the buyer is expected to reserve the right to renew the future contract(s).
`Award.hasRenewal` | Whether the buyer is expected to reserve the right to renew the future contract(s).
`Award.renewal` | The options for the renewal of the contract(s).
`Contract.hasRenewal` | Whether the buyer reserves the right to renew the contract.
`Contract.renewal` | The options for the renewal of the contract.

**Comment by jpmckinney** [comment]
Sounds good, I think we can omit "as long as the contract is valid" as we added that because of its equivalent in eForms – but I think it is obvious that a buyer cannot exercise its options if the contract is invalid/terminated.
