### ISSUE TITLE
Organization classification: broken links in the documentation

### ISSUE THREAD

**Issue by allakulov** [open-contracting/ocds-extensions#227]
The source links to the codes `TED_CA_TYPE` and `TED_CE_ACTIVITY` are broken in the Codelists [page](https://extensions.open-contracting.org/en/extensions/organizationClassification/master/codelists/) of the Organization classification extension documentation. It is likely due to TED schema forms having been replaced by eForms. The TED notice on a buyer profile, which contains the codes for the above schemes, is available [here.](https://ted.europa.eu/documents/d/ted/en_f08)

**Comment by jpmckinney** [comment]
Thanks! Where is that PDF linked from, btw?

**Comment by jpmckinney** [comment]
Fixed in open-contracting-extensions/ocds_organizationClassification_extension@e6ee6cc, but if you have a link for a page listing all the forms, I can use that link to fix a broken link elsewhere.

**Comment by jpmckinney** [comment]
Got it from Jen https://ted.europa.eu/en/simap/standard-ted-schema-forms-in-pdf
