### ISSUE TITLE
Lots: Rename minValue to minimumValue

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#235]
https://github.com/open-contracting-extensions/ocds_lots_extension/pull/33 closed https://github.com/open-contracting/ocds-extensions/issues/152 discussed as part of https://github.com/open-contracting/standard/issues/888

It uses `minValue` to match `tender/minValue`. However, for new fields, we typically expand acronyms. Also, UK FTS already implements tender/lots/minimumValue.

So, I think a rename is appropriate.

**Comment by odscjen** [comment]
@jpmckinney should we deprecate `minValue` and add an entirely new copy of the object, or simply rename it and note this in the changelog? I'm assuming the former as that's what would happen for the core standard?

**Comment by odscjen** [comment]
actually as the field was added as part of the "Unreleased" section in the changelog, just changing the name should be enough?

**Comment by jpmckinney** [comment]
Yes, since it's unreleased we can just make the change (including in the current changelog entry).

**Comment by Ben-Hickling** [comment]
> UK FTS already implements tender/lots/minimumValue.

Just noting for the record as it's quite tricky to find, minimum lot values are only possible in the F16 and F17 defence notices - in Annex B: Information about lots -> 3) Quantity or scope -> Range

Minimum values will not now be included in the new UK notices, with all values being maximums.
