### ISSUE TITLE
bid: tables not rendered in README.md file

### ISSUE THREAD

**Issue by edugomez** [open-contracting/ocds-extensions#25]
For example:
```
.. extensiontable::
   :extension: bids
   :exclude_definitions: statistics BidsStatistic
```

**Comment by jpmckinney** [comment]
But it is rendered on http://standard.open-contracting.org/latest/en/extensions/bids/

The solution is to either pre-render the table and paste it into the readme, or to just accept that people will have to visit http://standard.open-contracting.org/latest/en/extensions/bids/ instead.

I prefer the latter, so closing, but can re-open if there is disagreement.
