### ISSUE TITLE
Lots: Framework agreement call-offs with lots

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#29]
From discussion with @tomasposepny in Georgia:

Framework agreements are often divided into lots and mini-competitions for call-offs from the framework relate to a particular lot.

Based on the [framework guidance](http://standard.open-contracting.org/latest/en/implementation/related_processes/#framework-types), this would be represented in OCDS as multiple contracting processes using [relatedProcess](http://standard.open-contracting.org/latest/en/schema/reference/#relatedprocess) to link the processes for each mini-competition to the process for the initial setup of the framework.

Currently we lack a way to specify which lot in the framework the mini-competition relates to.

We discussed in Georgia adding a `relatedLot` property to the `relatedProcess` object to capture the `lot/id` from the framework which the mini-competition relates to.

**Comment by duncandewhurst** [comment]
There's a related discussion in CRM-7721

**Comment by jpmckinney** [comment]
Per the discussion in CRM-7721, at minimum `Award.relatedLots` should be set. Then, either:

* `tender.lots` should be restated in the mini-competition. In this way, the user discovers the lot in the usual way.
* `tender.lots` is not set. The user would have to instead look up `tender.lots` on the related process.

**Comment by jpmckinney** [comment]
I think the schema changes are sufficient. This is more a documentation issue, now.

**Comment by jpmckinney** [comment]
Yes, I think we misworded the original, and your suggestion looks good.

Is Ben on GitHub such that we can notify him here as well?

**Comment by odscjen** [comment]
I think so but I'm not sure of his handle, I've let him know via email.

**Comment by odscjen** [comment]
@jpmckinney suggested update to the [Framework](https://standard.open-contracting.org/latest/en/guidance/map/framework_agreements/#framework-types) guidance:

Add to [Relate the second stage to the first stage](https://standard.open-contracting.org/latest/en/guidance/map/framework_agreements/#relate-the-second-stage-to-the-first-stage)

* Add a `RelatedProcess` object to the `relatedProcesses` array, set its `.id` (to '1', for example), add 'framework' to its `.relationship` array, set its `.scheme` to 'ocid' and set its `.identifier` to the `ocid` of the invitation to participate in the framework agreement. **If the second stage relates to specific lots detailed in the first stage, add the `lots.id`'s from the invitation to participate to `.relatedLots`.**

The first example on the page wouldn't make sense to split into lots but the 2nd example could be. The 2nd example is based on a real process and links out to it so if we were to make a change to add in some lots I think that link would need to be removed as it would no longer be a real example (this links to the discussion in https://github.com/open-contracting/standard/pull/1661).

**Comment by jpmckinney** [comment]
Yes, it's okay to remove the external link.
