### ISSUE TITLE
Lots: Details of bids for specific lots

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#30]
Compare `Bid/relatedLots` against the `lotValues` approach in the open procurement API http://api-docs.openprocurement.org/en/latest/lots.html (from a `NOTE` field in the schema).

@timgdavies You authored this, so perhaps you know whether it's still relevant or can be closed?

**Comment by jpmckinney** [comment]
Closing as unresponsive and unclear if relevant.

**Comment by duncandewhurst** [comment]
I think the question probably related to whether our approach to linking bids and lots (a single bid value and list of relatedLots) was compatible with the Open Procurement API approach (a list of values associated with a bid, each linked to a lot)

**Comment by jpmckinney** [comment]
Related/Duplicate #138
