### ISSUE TITLE
Should extensions be translated in-situ?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#37]
I'm not clear how the translations of extensions are currently shared between the core standard and the PPP profile documentation. I'm also wondering how the translation of an extension will be shared across profiles, once we start publishing GPA, EU, UNCITRAL profiles.

**Comment by Bjwebb** [comment]
Translations were copied from the core OCDS docs to the PPP profile using `translate-toolkit`. This included both translations of extensions, but also those of the unextended schema.

**Comment by jpmckinney** [comment]
Cool, merging into https://github.com/open-contracting/standard-development-handbook/issues/70 to document how to do that.
