### ISSUE TITLE
Budget Breakdown: 

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds-extensions#39]
The [budget breakdown extension](https://github.com/open-contracting/ocds_budget_breakdown_extension) example incorrectly shows the budgetBreakdown property parallel to budget, when the schema shows it should be nested inside.

**Comment by timgdavies** [comment]
A PR to fix this at https://github.com/open-contracting/ocds_budget_breakdown_extension/pull/6 is currently blocked by some failing travis tests.

**Comment by jpmckinney** [comment]
Fixed by above PR.
