### ISSUE TITLE
Requirements: should only be used for selection criteria

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#4]
Originally reported by @timgdavies https://github.com/open-contracting/ocds_requirements_extension/issues/4

From work in Kiev:

(1) Requirements should only be for ``eligibilityCriteria`` which are pass/fail criteria applying to a bidder, **not** ``awardCriteria`` which can be evaluative criteria (pass/fail OR weighted) that apply to the item or the bidder. At the moment we suggest it can be used for both, and give an example based on properties of the item.

(2) Requirements may (in some cases) vary by ``lot`` - suggested a ```relatedLot``` property may be required in some cases. 

We identified a couple of terminological issues to clarify:

* Qualification criteria - pass/fail  - is the bidder eligible 'in general' to participate in procurement
* Eligibility criteria - pass/fail - is the bid eligible
* Selection criteria - weighted scoring - how should features of the bid or bidder be factored into the selection (against pricing criterial also)

We need to:

* [ ] (1) Evaluate where use of requirements is currently recommended;
* [ ] (2) Review whether we can use the requirements data model for award criteria, or whether the [ProZorro features approach](https://github.com/open-contracting/standard/issues/499) is appropriate for this
* [ ] (3) If (2) then check whether we should use the same object, but different properties for (e.g.) ``eligibilityCriteriaStructured`` and ``awardCriteriaStructured``

Note that EU might just need very simple awardCriteria breakdown to who balance between price and non-price criteria. 

Related issues:

* https://github.com/open-contracting/standard/issues/385#issuecomment-278358093
* https://github.com/open-contracting/standard/issues/499

**Comment by jpmckinney** [comment]
Original comment by @andrewlorien https://github.com/open-contracting/ocds_requirements_extension/issues/4#issuecomment-320578645

In NSW eTendering and AusTender (Australian commonwealth) there are criteria based on the CCCEV. They are never evaluated automatically, and many of the responses are documents (insurances, evidence of previous performance, qualifications etc).  Each criteria is given a pass/fail rating during the evaluation phase. These are prequalifications, so a contract is not directly awarded based on the status of the criteria.
Based on Tim's comment, we would have an Eligibility Criteria for each item, and (I assume) when every item passes the tenderer becomes qualified.  From the information on this ticket at the moment, I can't decide where the pass/fail for each individual item would go.  Working on that this week.

**Comment by timgdavies** [comment]
Removing @duncandewhurst from assignment (as heading on leave), adding @jpmckinney to assigned as I believe this is linked to work on EU and GPA extensions.

**Comment by jpmckinney** [comment]
With respect to a bid's eligibility, the Kyrgyz e-GP system has a web form with a subform containing a dropdown for technical requirements (i.e. using a code list) as well as a free-text field (for expanding the code list), which when submitted is added as a row to a table of technical requirements. It also has a single file attachment field, for technical requirements relating to the whole tender.

The selection committee has some discretion with respect to how the technical requirements are applied (for example, they may not apply to every lot). These requirements can be modelled using a new object. The object’s fields that we need at a minimum are a `type` field (which would use an open codelist) and a `description` field, to match what is in the Kyrgyz e-GP system. If we were to consider how this new object can be used by other publishers, we may want to add fields for`id`, `title` and `relatedLots`.

**Comment by jpmckinney** [comment]
OCDS has clarified the distinctions between eligibility, selection criteria, exclusion grounds, and award criteria.

This extension own documentation isn't confused about its purpose (selection criteria), so there is nothing to do. Closing.
