### ISSUE TITLE
Budget Projects: Add content from descriptions back

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#46]
The budget projects extension had been overwriting titles/descriptions from the core standard, which isn't preferred.

It also deletes the `source` field (#17), despite its being already deprecated in the standard, and removes `integer` as a valid Budget/id type.

* Budget/description: This section contains basic information about the budget estimated for, or allocated to, this contracting process at the present time. Further documentation and data about how budgets have been allocated to a contracting process should be published outside of OCDS data, according to the best available standards.
* Budget/properties/id/description: An identifier for the budget line item which provides funds for this contracting process. Wherever possible, this identifier should be possible to cross-reference against formal budget documents.
* Budget/properties/description/description: A short free text description of the budget allocation for this contracting process. This may be used to provide human readable information on the budget category allocated to this contracting process, and/or, information about the nature and source of the allocation (e.g. conditional, confirmed; any official authorizations given to the budget allocation).
* Budget/properties/amount/description: The total value of budget allocations for this contracting process. The budget breakdown extension can be used to provide data for multiple budget sources, or to split the budget by years or other periods.
* Budget/properties/project/description: The name of the project that through which this contracting process is funded. Detailed information should be provided in the extended projectDetail section.
* Budget/properties/projectID/description: An external identifier for the project that this contracting process forms part of. Required for legacy compatibility with OCDS core.
* Budget/properties/uri/description: A URI pointing directly to records about the related budget for this contracting process. Where possible this URI should return machine and human-readable representations of the data.

Descriptions should be improved in the core standard, not in extensions, as that risks extensions changing the semantics of the standard.

Another option is to just add the content from the updated descriptions to the extension's documentation (README.md).

**Comment by jpmckinney** [comment]
@duncandewhurst Perhaps an issue to prioritize for PPPs. I think we can add this content to the readme, as extensions should be redefining fields from the core.

**Comment by duncandewhurst** [comment]
I've added these descriptions to a "guidance" section in the extension readme, removing truly duplicated information where appropriate (see https://github.com/open-contracting/ocds_budget_projects_extension/pull/12)
