### ISSUE TITLE
participationFees: Add `id` field to array of objects

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#48]
https://github.com/open-contracting/standard-development-handbook/pull/107 states "Any object that is contained within an array MUST have an `id` field."

`ParticipationFee` has no `id` field, but is an object in an array.

**Comment by yolile** [comment]
Shouldn't the id field be required?

**Comment by jpmckinney** [comment]
Unfortunately we can't add new requirements to core extensions until OCDS 2.0. https://github.com/open-contracting/standard/issues/650#issuecomment-361313888

**Comment by yolile** [comment]
Can we then at least update the readme and example?

**Comment by jpmckinney** [comment]
Have a look now: https://github.com/open-contracting-extensions/ocds_participationFee_extension

**Comment by jpmckinney** [comment]
(Will be built here within 24 hours: https://extensions.open-contracting.org/en/extensions/participation_fee/master/)

**Comment by yolile** [comment]
Great, thanks James!
