### ISSUE TITLE
Rename ocds_multiple_buyers_extension to ocds_contractLevel_buyer

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds-extensions#51]
We have an OCDS extension called [ocds_multiple_buyers_extension](https://github.com/open-contracting/ocds_multiple_buyers_extension) which actually adds a single buyer to each contract, and in the readme and extensions registry [we call it 'Buyer per contract'](https://github.com/open-contracting/extension_registry/blob/master/buyer_per_contract/entry.json)

It also has the non-descriptive slug "contract". 

@transpresupuestaria have proposed adding an extension called [ocds_multiple_buyers_extension](https://github.com/transpresupuestaria/ocds_multiple_buyers_extension) which better deserves the name. 

We should consider renaming the repo, and updating the slug and extension repository accordingly. 

This might require an update to scripts for PPP profile generation.

**Comment by jpmckinney** [comment]
Sounds reasonable. I made a note to myself to inspect all slugs and folder names in the registry. Also related: https://github.com/open-contracting/extension_registry/issues/69

**Comment by jpmckinney** [comment]
To avoid breaking URLs, I think we'll leave the repo URL and slug as-is (same reason we haven't moved all extensions to the open-contracting-extensions organization). The repo URL only appears in the list of `extensions`, and the slug only appears in URLs within documentation, so the impact is minimal.

**Comment by jpmckinney** [comment]
It appears that GitHub uses internal redirects when making requests to `raw.githubusercontent.com`, e.g.:

    curl -I https://raw.githubusercontent.com/open-contracting/extension_tester/master/LICENSE

is the same as:

    curl -I https://raw.githubusercontent.com/open-contracting-archive/extension_tester/master/LICENSE

(Note that https://github.com/open-contracting/extension_tester/blob/master/LICENSE, on the other hand, results in HTTP 301.)

Since changing the repository name wouldn't require users to handle 301 redirects, I'm re-opening the issue.

**Comment by jpmckinney** [comment]
Changed repo name https://github.com/open-contracting/extension_registry/commit/2dae3b5d88e72cbea24e3043ef99e8229ad4a8b2 and slug in https://github.com/open-contracting/extension_registry/commit/34a4b1636abec98fdbe0c213dc99aae40e78aa99
