### ISSUE TITLE
META: Define and fix Category column in codelist CSV files

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#56]
Core values for `Category` are `basic`, `intermediate` and `advanced`, i.e. `Category` means the BIA category in core. Extensions use it differently:

* [ocds-riskAllocation-extension](https://github.com/open-contracting/ocds-riskAllocation-extension/blob/master/codelists/riskCategory.csv)
* [ocds_bid_extension](https://github.com/open-contracting/ocds_bid_extension/blob/master/codelists/bidStatistics.csv)
* [ocds_location_extension](https://github.com/open-contracting/ocds_location_extension/blob/master/codelists/locationGazetteers.csv)

Also, strange to me that `bidStatistics.csv` has `EU` as a category. Surely not only EU cares about "Bids from SMEs".

**Comment by timgdavies** [comment]
I believe category is only used in core for the [documentType](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/codelists/documentType.csv) codelist. 

It was intended to support filtering of the list, to identify those documents that publishers are encouraged to consider at each level. 

In the other extensions, it also acts a means to filter / select relevant codelist entries, though it is also acting as a means of indicating the source of certain codelist entries. For example, the EU code in bidStatistics indicates that the definition of the statistic was taken from EU requirements, and this specific statistical definition of EU specific. 

We might narrowly define the semantics of category as as:

> A category column MAY be included to support user interfaces to sort and filter codelist values. 

Given this, we **could** allow one-to-many categorisations, but for simplicity, I suggest we allow only a single value for now, but consider how any future work on codelist management / master data management might allow greater flexibility. 

We could either just leave the information on the source/relevance of the codes implied, or we could re-introduce a `source` or `notes` column, where more detailed information of this form would be provided. 

We might also add:

> Where the Category column is included by an extension, the documentation for that extension should explain the nature of the categorisation.

Which would then give:

* [ocds-riskAllocation-extension](https://github.com/open-contracting/ocds-riskAllocation-extension/blob/master/codelists/riskCategory.csv) - The category column is used to group types of risk in relation to the stage or aspect of the contracting process they apply to. 
* [ocds_bid_extension](https://github.com/open-contracting/ocds_bid_extension/blob/master/codelists/bidStatistics.csv) - The category column is used to indicate statistics that apply to bids, bidders or that are specified or required by a particular reporting regime (e.g. EU).
* [ocds_location_extension](https://github.com/open-contracting/ocds_location_extension/blob/master/codelists/locationGazetteers.csv) - The category column is used to indicated whether the list will include codes for the whole world (Universal) or only some sub-set (Sub-National). 

The category values in [ocds_location_extension](https://github.com/open-contracting/ocds_location_extension/blob/master/codelists/locationGazetteers.csv) don't make much sense to me on reviewing them, so may also need changing.

**Comment by jpmckinney** [comment]
Thanks! I'll make some PRs at a later date for these.
