### ISSUE TITLE
META: Set documentationUrl to standard documentation for core extensions?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#65]
For core extensions, the registry set `documentationUrl` to, e.g. http://standard.open-contracting.org/1.1/en/extensions/bids/ whereas the core extensions' `extension.json` set it to, e.g. https://github.com/open-contracting/ocds_bid_extension

Should we update all the core extensions' `extension.json` to refer to the standard documentation?

**Comment by jpmckinney** [comment]
I assume we should to maintain the prior behaviour. Do you agree, @duncandewhurst or @timgdavies ?

**Comment by duncandewhurst** [comment]
I think the difference is down to the standard documentation pages not existing when the `extension.json` files were created.

In terms of where the `documentationURL` is used, the schema reference and extensions table in the docs look like they use the extension registry value and I think CoVE [should use the registry too](https://github.com/OpenDataServices/cove/issues/704)), so it should be OK to update the version in `extension.json` to match the extension registry unless it is used anywhere else.

**Comment by jpmckinney** [comment]
Assuming I understood your proposal, I authored pull requests to use URLs like http://standard.open-contracting.org/1.1/en/extensions/bids/ as the `documentationUrl` of pull requests.

The [PR for the new registry format](https://github.com/open-contracting/standard/pull/724) is built at http://standard.open-contracting.org/registry/en/extensions/#core-extensions, which would continue to use URLs like `https://github.com/open-contracting/ocds_bid_extension`, because with the new registry, `documentationUrl` values are taken from specific versions of core extensions. In the old registry, we duplicated `name`, `description`, `documentationUrl`, which meant that we can override (both deliberately and accidentally) the values in `extension.json`.

**Comment by duncandewhurst** [comment]
@timgdavies what do you think?

**Comment by jpmckinney** [comment]
@timgdavies Any word? I'll merge next Monday if no word, as the impact of these PRs is to restore behavior in the development version of the standard, which only changed recently due to changes to the registry format (as described above).
