### ISSUE TITLE
META: Appropriate values for compatibility array

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#66]
See earlier discussion in https://github.com/open-contracting/ocds-extensions/issues/59#issuecomment-396088596

`compatibility` is [defined](https://github.com/open-contracting/standard_extension_template) as "An array of minor versions of the core standard that the extension is compatible with".

Some extensions have no `compatibility` array. Some list 1.1 only. Some list both 1.0 and 1.1.

I agree with @duncandewhurst (see linked discussion) that we should not have 1.0 as a valid value, and that we should update all extensions to list 1.1 only.

Would you agree @timgdavies ? If so, I can make and merge the PRs.

**Comment by timgdavies** [comment]
I'd be happy to say extensions are only compatible with 1.1 upwards, given prior to this we had a different and less documented extensions approach.
