### ISSUE TITLE
META: Move all extensions from open-contracting to open-contracting-extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#68]
As I noticed in https://github.com/open-contracting/ocds-extensions/issues/51#issuecomment-423204398, if repositories are moved between organizations, the `raw.githubusercontent.com` link still works (without any redirects, i.e. it returns the appropriate content with HTTP 200).

As such, it's possible to move all extensions from open-contracting to open-contracting-extensions without breaking URLs (or causing redirects) in the `extensions` array of OCDS packages.

The `github.com` URLs to extension repositories are only used in hypertext (not in machine-readable text like the `extensions` array), and those will redirect in the browser.

So, this issue is to get agreement on moving all extensions from open-contracting to open-contracting-extensions.

Moving extensions would follow the reasons for having a separate open-contracting-extensions organization in the first place, the major reasons being:

* relevant repositories in open-contracting become hard to find and browse when they are buried in a large and growing number of extensions
* open-contracting is perceived as being 'owned' by OCP and may discourage participation and contributions

Sub-tasks:

* [x] Move all extensions from open-contracting to open-contracting-extensions
* [x] Update URLs in extension registry

Assigning Duncan for standard governance perspective, James for extension explorer / data collector perspective, and Rob for broader technical perspective.

**Comment by odscjames** [comment]
>  if repositories are moved between organizations, the raw.githubusercontent.com link still works (without any redirects

Do we know for how long after the rename this is true? Will this move be accompanied by a push to get all current publishers to change the extensions URL in any data they publish, in case something happens to the redirect in the future?


Apart from that, I don't forsee any technical issues in the extension explorer / data collector. 

We could maybe even add a column to  https://github.com/open-contracting/extension_registry/blob/master/extensions.csv called "Old GitHub Repository" with data of the type "https://github.com/open-contracting/xxxxxx". Then if in the future we realise we do need to be able to rewrite old URLs to new ones, we will have the data to let us do so.

**Comment by jpmckinney** [comment]
I forget when I moved repos to open-contracting-archive, but it was at least six months ago, and the internal redirects still work. This, along with [GitHub's documentation](https://help.github.com/articles/renaming-a-repository/), suggests that the redirect is permanent (until GitHub changes how it provides access to raw files, but if it changes that, likely all our URLs will break).

We can schedule this with a release of OCDS to announce the change to publishers. With Kingfisher, we can tell which publishers use extensions, and follow-up individually.

**Comment by jpmckinney** [comment]
See also this GitHub documentation: https://help.github.com/articles/about-repository-transfers/

This is now done. I've made a note to follow up with publishers.
