### ISSUE TITLE
codes for ocds_coveredBy_extension

### ISSUE THREAD

**Issue by myroslav** [open-contracting/ocds-extensions#70]
Machine interpretation and filtering for tenders covered by GPA can be complex if the extension allows only text-only description.

Please consider every element of the array to be a `Treaty` objects with open-codelit `id` & `title`. Example of such object is below:
```json
{
  "id": "gpa",
  "title": "Contract is covered by the GPA."
}
```

**Comment by jpmckinney** [comment]
The extension is currently implemented as an [open codelist](https://github.com/open-contracting-extensions/ocds_coveredBy_extension/blob/master/release-schema.json). The [codelist](https://github.com/open-contracting-extensions/ocds_coveredBy_extension/blob/master/codelists/coveredBy.csv) currently only has GPA.

Is there an issue with using a codelist? I believe it preserves machine interpretation, as the code for GPA, for example, will always be the same if the implementation uses the codelist.

**Comment by myroslav** [comment]
Sorry, I didn't invest enough time into investigation of extension sources, and relied my feedback only on the [README.md](https://github.com/open-contracting-extensions/ocds_coveredBy_extension/blob/master/README.md), thus assumed that value expected is free-text explanation of the treaty.

Given the fact that property IS CODELIST-ed, I see no problem in extension itself. Feel free to close the bug, or update README to mention that there is open codelist of proposed values to be used.

**Comment by jpmckinney** [comment]
I'll keep this issue open to update the readme.
