### ISSUE TITLE
participationFees, Bids: Indicating that the submission fee for a bid has been paid

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds-extensions#74]
Draft data from Belarus adds a `paid` field to the `Bid` object to indicate whether the submission fee for a bid has been paid. Helpdesk suggested in feedback that this should be renamed to `submissionFeePaid`

**Comment by jpmckinney** [comment]
It will depend on implementer research, but we might want each bid to be able to share the payment status of different [participation fees](https://github.com/open-contracting-extensions/ocds_participationFee_extension/blob/master/release-schema.json). In that case, we might have a `participationFees` array on the bid, whose objects include at least `participationFeeID` and `status`, a codelist with at least 'unpaid', 'paid' and 'refunded' #28 codes.

**Comment by duncandewhurst** [comment]
Of the publications in OCDS Downloads that use participation fees, only `india_civic_data_labs` has multiple fees per contracting process:

publication | max(participationFee_count)
-- | --
honduras_oncae | 1
india_civic_data_lab | 2
scotland_public_contracts | 1
uk_fts | 1

Given that the participation fees extension permits multiple fees per contracting process, that the codes in `participationFeeType.csv` are not mutually exclusive, and that we have evidence of at least one implementer with multiple fees per contracting process, your proposal sounds good.

Happy for me to create a PR?

**Comment by jpmckinney** [comment]
So far I think we have only Belarus that has data on payment status, correct? If so, we can leave this issue open, as it's best to standardized based on at least two real implementations/sources.

**Comment by duncandewhurst** [comment]
> So far I think we have only Belarus that has data on payment status, correct? If so, we can leave this issue open, as it's best to standardize based on at least two real implementations/sources.

As far as I'm aware, yep. Should we move this out of the 1.2 milestone then?

**Comment by jpmckinney** [comment]
Done!

**Comment by jpmckinney** [comment]
It's been a few years with only evidence of payment status from one country (which did not make its dataset public). I'll close, as I'm not sure many systems disclose this information. I'm also not clear on its use cases.
