### ISSUE TITLE
META: Add contactPoint to extension.json

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#78]
e.g. 

```json
{
  "contactPoint": {
    "name": "J",
    "email": "j@example.com"
  }
}
```

Also, update the standard_extension_template's extension.json and readme, and update standard-maintenance-scripts' extension-schema.json.

Then, we can integrate contact points into the extension explorer.

Moved from https://github.com/open-contracting/extension_registry/issues/97

**Comment by jpmckinney** [comment]
> Does "OCDS Helpdesk" and "data@open-contracting.org" as email sound good?

Let's use "Open Contracting Partnership" for the name.

In terms of approach, I suggest making the changes to `standard_extension_template` and `standard-maintenance-scripts`. I also recently restored a `local:extension_json` Rake task in standard-maintenance-scripts, which we can fill in to make changes to extensions.

Once that's done, I can run the Rake task and update all our extensions.

**Comment by romifz** [comment]
I understand, thanks for the clarifications.

**Comment by jpmckinney** [comment]
I ran the Rake task and updated all our extensions 🎉 

I created the follow-up issue: https://github.com/open-contracting/extension-explorer/issues/55
