### ISSUE TITLE
participationFees: Use codelist developed by INAI Mexico

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#93]
https://github.com/open-contracting-extensions/ocds_participationFee_extension

https://github.com/INAImexico/ocds_paymentMethod_extension/blob/master/codelists/paymentMethod.csv

See discussion in https://github.com/open-contracting/standard/issues/622

**Comment by yolile** [comment]
@jpmckinney should we copy the csv or add the INAI extension as a dependency and reference the codelist that is defined there? or should we do the first and reference the INAI extension in the README?

**Comment by jpmckinney** [comment]
Sorry, I missed this update. We should copy the CSV. However, I see there's a typo (`wireTransfe` instead of `wireTransfer`).

**Comment by jpmckinney** [comment]
@yolile Is this still in progress, or should it be reassigned?
