### ISSUE TITLE
Bids: Make reusable for quotes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-extensions#94]
See https://github.com/open-contracting/standard/issues/599#issuecomment-468545925

We might want to add/edit fields on `Bid` based on `Quote`, including:

* bid description
* bid validity period
* bid items

**Comment by duncandewhurst** [comment]
There's already an issue for adding items to `Bid`: https://github.com/open-contracting/ocds-extensions/issues/126

Adding `Bid.description` and `Bid.validityPeriod` seem unlikely to cause any issues.

In terms of edits to existing fields, I think it would be sufficient to:

1. Update the description of `Bid` to read (changes in italics):

> For representing a bid *or quote* in response to the tender or qualification stage in this contracting process.

2. Add a note to the readme to explain that the extension can also be used to represent quotes.

@jpmckinney happy to proceed on that basis?

**Comment by jpmckinney** [comment]
Yes, sounds good. In some jurisdictions, bid and quote are used interchangeably; in others, it seems there might be a difference. At any rate, "bid or quote" can cover either case.
